In [1]:
!curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash

--2023-11-19 08:01:00--  https://www.dropbox.com/s/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz [following]
--2023-11-19 08:01:00--  https://www.dropbox.com/s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucd1dcd4ed9a50f9a02b3ff992f1.dl.dropboxusercontent.com/cd/0/get/CH2PucyuSV_nbEd-nTaBxgpIhMvtT6sra-CnZhj1Jh6MvEbEdP4jppD9Pccd9RcvGsp0F_z-HADUdGl1WjZjf48se9nIrMyVOo1hW2tyZ4A12TpGmKMnc1TIoiRk9b59YDZQZ5hBgfKD0yQBJpRy5WeV/file?dl=1# [following]
--2023-11-19 08:01:00--  https://ucd1dcd4ed9a50f9a02b3ff992f1.dl.dropboxusercontent.com/cd/0/get/CH2PucyuSV_nbEd-nTaBxgpIhMvtT6sra-CnZhj1Jh6MvEbEdP4jppD9Pccd9RcvGsp0F_z-HADUdGl1WjZjf48se9nIrMyVOo1hW2tyZ4A12TpGmKMnc1TIoiRk9b59YDZQZ5hBgfKD0yQBJpRy5WeV/file?dl=1
Resolving ucd1dcd4ed9a50f9a02b3ff992f1.dl.dropboxusercontent.com (ucd1dcd4ed9a50f9a02b3ff992f1.dl.dropboxusercontent.com)... 162.125.3.15, 2620:100:6018:15::a27d:30f
Connecting to ucd1dcd4ed9a50f9a02b3ff992f1.dl.dropboxusercontent.com (ucd1dcd4ed9a50f9a02b3ff992f1.dl.dropboxusercontent.com)|162.125.3.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1414979 (1.3M) [application/binary]
Saving to: ‘mecab-0.996-ko-0.9.2.tar.gz?dl=1’

mecab-0.996-ko-0.9. 100%[===================>]   1.35M  --.-KB/s    in 0.07s

2023-11-19 08:01:01 (19.5 MB/s) - ‘mecab-0.996-ko-0.9.2.tar.gz?dl=1’ saved [1414979/1414979]

mecab-0.996-ko-0.9.2/
mecab-0.996-ko-0.9.2/example/
mecab-0.996-ko-0.9.2/example/example.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.c
mecab-0.996-ko-0.9.2/example/example.c
mecab-0.996-ko-0.9.2/example/thread_test.cpp
mecab-0.996-ko-0.9.2/mecab-config.in
mecab-0.996-ko-0.9.2/man/
mecab-0.996-ko-0.9.2/man/Makefile.am
mecab-0.996-ko-0.9.2/man/mecab.1
mecab-0.996-ko-0.9.2/man/Makefile.in
mecab-0.996-ko-0.9.2/mecab.iss.in
mecab-0.996-ko-0.9.2/config.guess
mecab-0.996-ko-0.9.2/README
mecab-0.996-ko-0.9.2/COPYING
mecab-0.996-ko-0.9.2/CHANGES.md
mecab-0.996-ko-0.9.2/README.md
mecab-0.996-ko-0.9.2/INSTALL
mecab-0.996-ko-0.9.2/config.sub
mecab-0.996-ko-0.9.2/configure.in
mecab-0.996-ko-0.9.2/swig/
mecab-0.996-ko-0.9.2/swig/Makefile
mecab-0.996-ko-0.9.2/swig/version.h.in
mecab-0.996-ko-0.9.2/swig/version.h
mecab-0.996-ko-0.9.2/swig/MeCab.i
mecab-0.996-ko-0.9.2/aclocal.m4
mecab-0.996-ko-0.9.2/LGPL
mecab-0.996-ko-0.9.2/Makefile.am
mecab-0.996-ko-0.9.2/configure
mecab-0.996-ko-0.9.2/tests/
mecab-0.996-ko-0.9.2/tests/autolink/
mecab-0.996-ko-0.9.2/tests/autolink/unk.def
mecab-0.996-ko-0.9.2/tests/autolink/dicrc
mecab-0.996-ko-0.9.2/tests/autolink/dic.csv
mecab-0.996-ko-0.9.2/tests/autolink/test
mecab-0.996-ko-0.9.2/tests/autolink/char.def
mecab-0.996-ko-0.9.2/tests/autolink/matrix.def
mecab-0.996-ko-0.9.2/tests/autolink/test.gld
mecab-0.996-ko-0.9.2/tests/t9/
mecab-0.996-ko-0.9.2/tests/t9/unk.def
mecab-0.996-ko-0.9.2/tests/t9/ipadic.pl
mecab-0.996-ko-0.9.2/tests/t9/dicrc
mecab-0.996-ko-0.9.2/tests/t9/dic.csv
mecab-0.996-ko-0.9.2/tests/t9/test
mecab-0.996-ko-0.9.2/tests/t9/char.def
mecab-0.996-ko-0.9.2/tests/t9/matrix.def
mecab-0.996-ko-0.9.2/tests/t9/mkdic.pl
mecab-0.996-ko-0.9.2/tests/t9/test.gld
mecab-0.996-ko-0.9.2/tests/cost-train/
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.train
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.test
mecab-0.996-ko-0.9.2/tests/cost-train/seed/
mecab-0.996-ko-0.9.2/tests/cost-train/seed/rewrite.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/feature.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/unk.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dicrc
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dic.csv
mecab-0.996-ko-0.9.2/tests/cost-train/seed/char.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/matrix.def
mecab-0.996-ko-0.9.2/tests/run-eval.sh
mecab-0.996-ko-0.9.2/tests/run-cost-train.sh
mecab-0.996-ko-0.9.2/tests/Makefile.am
mecab-0.996-ko-0.9.2/tests/katakana/
mecab-0.996-ko-0.9.2/tests/katakana/unk.def
mecab-0.996-ko-0.9.2/tests/katakana/dicrc
mecab-0.996-ko-0.9.2/tests/katakana/dic.csv
mecab-0.996-ko-0.9.2/tests/katakana/test
mecab-0.996-ko-0.9.2/tests/katakana/char.def
mecab-0.996-ko-0.9.2/tests/katakana/matrix.def
mecab-0.996-ko-0.9.2/tests/katakana/test.gld
mecab-0.996-ko-0.9.2/tests/eval/
mecab-0.996-ko-0.9.2/tests/eval/answer
mecab-0.996-ko-0.9.2/tests/eval/system
mecab-0.996-ko-0.9.2/tests/eval/test.gld
mecab-0.996-ko-0.9.2/tests/shiin/
mecab-0.996-ko-0.9.2/tests/shiin/unk.def
mecab-0.996-ko-0.9.2/tests/shiin/dicrc
mecab-0.996-ko-0.9.2/tests/shiin/dic.csv
mecab-0.996-ko-0.9.2/tests/shiin/test
mecab-0.996-ko-0.9.2/tests/shiin/char.def
mecab-0.996-ko-0.9.2/tests/shiin/matrix.def
mecab-0.996-ko-0.9.2/tests/shiin/mkdic.pl
mecab-0.996-ko-0.9.2/tests/shiin/test.gld
mecab-0.996-ko-0.9.2/tests/latin/
mecab-0.996-ko-0.9.2/tests/latin/unk.def
mecab-0.996-ko-0.9.2/tests/latin/dicrc
mecab-0.996-ko-0.9.2/tests/latin/dic.csv
mecab-0.996-ko-0.9.2/tests/latin/test
mecab-0.996-ko-0.9.2/tests/latin/char.def
mecab-0.996-ko-0.9.2/tests/latin/matrix.def
mecab-0.996-ko-0.9.2/tests/latin/test.gld
mecab-0.996-ko-0.9.2/tests/chartype/
mecab-0.996-ko-0.9.2/tests/chartype/unk.def
mecab-0.996-ko-0.9.2/tests/chartype/dicrc
mecab-0.996-ko-0.9.2/tests/chartype/dic.csv
mecab-0.996-ko-0.9.2/tests/chartype/test
mecab-0.996-ko-0.9.2/tests/chartype/char.def
mecab-0.996-ko-0.9.2/tests/chartype/matrix.def
mecab-0.996-ko-0.9.2/tests/chartype/test.gld
mecab-0.996-ko-0.9.2/tests/run-dics.sh
mecab-0.996-ko-0.9.2/tests/ngram/
mecab-0.996-ko-0.9.2/tests/ngram/unk.def
mecab-0.996-ko-0.9.2/tests/ngram/dicrc
mecab-0.996-ko-0.9.2/tests/ngram/dic.csv
mecab-0.996-ko-0.9.2/tests/ngram/test
mecab-0.996-ko-0.9.2/tests/ngram/char.def
mecab-0.996-ko-0.9.2/tests/ngram/matrix.def
mecab-0.996-ko-0.9.2/tests/ngram/test.gld
mecab-0.996-ko-0.9.2/tests/Makefile.in
mecab-0.996-ko-0.9.2/ltmain.sh
mecab-0.996-ko-0.9.2/config.rpath
mecab-0.996-ko-0.9.2/config.h.in
mecab-0.996-ko-0.9.2/mecabrc.in
mecab-0.996-ko-0.9.2/GPL
mecab-0.996-ko-0.9.2/Makefile.train
mecab-0.996-ko-0.9.2/ChangeLog
mecab-0.996-ko-0.9.2/install-sh
mecab-0.996-ko-0.9.2/AUTHORS
mecab-0.996-ko-0.9.2/doc/
mecab-0.996-ko-0.9.2/doc/bindings.html
mecab-0.996-ko-0.9.2/doc/posid.html
mecab-0.996-ko-0.9.2/doc/unk.html
mecab-0.996-ko-0.9.2/doc/learn.html
mecab-0.996-ko-0.9.2/doc/format.html
mecab-0.996-ko-0.9.2/doc/libmecab.html
mecab-0.996-ko-0.9.2/doc/mecab.css
mecab-0.996-ko-0.9.2/doc/feature.html
mecab-0.996-ko-0.9.2/doc/Makefile.am
mecab-0.996-ko-0.9.2/doc/soft.html
mecab-0.996-ko-0.9.2/doc/en/
mecab-0.996-ko-0.9.2/doc/en/bindings.html
mecab-0.996-ko-0.9.2/doc/dic-detail.html
mecab-0.996-ko-0.9.2/doc/flow.png
mecab-0.996-ko-0.9.2/doc/mecab.html
mecab-0.996-ko-0.9.2/doc/index.html
mecab-0.996-ko-0.9.2/doc/result.png
mecab-0.996-ko-0.9.2/doc/doxygen/
mecab-0.996-ko-0.9.2/doc/doxygen/tab_a.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals_eval.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_vars.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.css
mecab-0.996-ko-0.9.2/doc/doxygen/tab_r.gif
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h_source.html
mecab-0.996-ko-0.9.2/doc/doxygen/tabs.css
mecab-0.996-ko-0.9.2/doc/doxygen/nav_f.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals.html
mecab-0.996-ko-0.9.2/doc/doxygen/nav_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/closed.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_l.gif
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/tab_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaces.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaceMeCab.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/files.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/index.html
mecab-0.996-ko-0.9.2/doc/doxygen/annotated.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_defs.html
mecab-0.996-ko-0.9.2/doc/doxygen/classes.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h-source.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.gif
mecab-0.996-ko-0.9.2/doc/doxygen/bc_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/open.png
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h.html
mecab-0.996-ko-0.9.2/doc/dic.html
mecab-0.996-ko-0.9.2/doc/partial.html
mecab-0.996-ko-0.9.2/doc/feature.png
mecab-0.996-ko-0.9.2/doc/Makefile.in
mecab-0.996-ko-0.9.2/missing
mecab-0.996-ko-0.9.2/BSD
mecab-0.996-ko-0.9.2/NEWS
mecab-0.996-ko-0.9.2/mkinstalldirs
mecab-0.996-ko-0.9.2/src/
mecab-0.996-ko-0.9.2/src/dictionary.h
mecab-0.996-ko-0.9.2/src/writer.h
mecab-0.996-ko-0.9.2/src/utils.h
mecab-0.996-ko-0.9.2/src/string_buffer.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.cpp
mecab-0.996-ko-0.9.2/src/make.bat
mecab-0.996-ko-0.9.2/src/mecab.h
mecab-0.996-ko-0.9.2/src/freelist.h
mecab-0.996-ko-0.9.2/src/string_buffer.h
mecab-0.996-ko-0.9.2/src/learner_tagger.h
mecab-0.996-ko-0.9.2/src/dictionary_compiler.cpp
mecab-0.996-ko-0.9.2/src/eval.cpp
mecab-0.996-ko-0.9.2/src/mecab-system-eval.cpp
mecab-0.996-ko-0.9.2/src/darts.h
mecab-0.996-ko-0.9.2/src/param.h
mecab-0.996-ko-0.9.2/src/char_property.h
mecab-0.996-ko-0.9.2/src/learner_node.h
mecab-0.996-ko-0.9.2/src/mecab-dict-gen.cpp
mecab-0.996-ko-0.9.2/src/mecab-dict-index.cpp
mecab-0.996-ko-0.9.2/src/winmain.h
mecab-0.996-ko-0.9.2/src/thread.h
mecab-0.996-ko-0.9.2/src/context_id.cpp
mecab-0.996-ko-0.9.2/src/Makefile.am
mecab-0.996-ko-0.9.2/src/connector.h
mecab-0.996-ko-0.9.2/src/common.h
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.cpp
mecab-0.996-ko-0.9.2/src/Makefile.msvc.in
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.h
mecab-0.996-ko-0.9.2/src/feature_index.h
mecab-0.996-ko-0.9.2/src/iconv_utils.cpp
mecab-0.996-ko-0.9.2/src/char_property.cpp
mecab-0.996-ko-0.9.2/src/mecab-test-gen.cpp
mecab-0.996-ko-0.9.2/src/tagger.cpp
mecab-0.996-ko-0.9.2/src/mecab-cost-train.cpp
mecab-0.996-ko-0.9.2/src/learner.cpp
mecab-0.996-ko-0.9.2/src/dictionary.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.cpp
mecab-0.996-ko-0.9.2/src/ucs.h
mecab-0.996-ko-0.9.2/src/writer.cpp
mecab-0.996-ko-0.9.2/src/learner_tagger.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.h
mecab-0.996-ko-0.9.2/src/libmecab.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.h
mecab-0.996-ko-0.9.2/src/mecab.cpp
mecab-0.996-ko-0.9.2/src/utils.cpp
mecab-0.996-ko-0.9.2/src/dictionary_generator.cpp
mecab-0.996-ko-0.9.2/src/param.cpp
mecab-0.996-ko-0.9.2/src/context_id.h
mecab-0.996-ko-0.9.2/src/mmap.h
mecab-0.996-ko-0.9.2/src/viterbi.h
mecab-0.996-ko-0.9.2/src/viterbi.cpp
mecab-0.996-ko-0.9.2/src/stream_wrapper.h
mecab-0.996-ko-0.9.2/src/feature_index.cpp
mecab-0.996-ko-0.9.2/src/nbest_generator.h
mecab-0.996-ko-0.9.2/src/ucstable.h
mecab-0.996-ko-0.9.2/src/nbest_generator.cpp
mecab-0.996-ko-0.9.2/src/iconv_utils.h
mecab-0.996-ko-0.9.2/src/connector.cpp
mecab-0.996-ko-0.9.2/src/Makefile.in
mecab-0.996-ko-0.9.2/src/scoped_ptr.h
mecab-0.996-ko-0.9.2/Makefile.in
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing strerror... none required
checking whether byte ordering is bigendian... no
checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for ANSI C header files... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... (cached) no
checking for string.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking for sys/types.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for sys/types.h... (cached) yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for off_t... yes
checking for size_t... yes
checking size of char... 1
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of size_t... 8
checking for size_t... (cached) yes
checking for unsigned long long int... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for main in -lstdc++... yes
checking for pthread_create in -lpthread... yes
checking for pthread_join in -lpthread... yes
checking for getenv... yes
checking for opendir... yes
checking whether make is GNU Make... yes
checking if g++ supports stl <vector> (required)... yes
checking if g++ supports stl <list> (required)... yes
checking if g++ supports stl <map> (required)... yes
checking if g++ supports stl <set> (required)... yes
checking if g++ supports stl <queue> (required)... yes
checking if g++ supports stl <functional> (required)... yes
checking if g++ supports stl <algorithm> (required)... yes
checking if g++ supports stl <string> (required)... yes
checking if g++ supports stl <iostream> (required)... yes
checking if g++ supports stl <sstream> (required)... yes
checking if g++ supports stl <fstream> (required)... yes
checking if g++ supports template <class T> (required)... yes
checking if g++ supports const_cast<> (required)... yes
checking if g++ supports static_cast<> (required)... yes
checking if g++ supports reinterpret_cast<> (required)... yes

In [2]:
from konlpy.tag import Okt
okt = Okt()

In [3]:
!pip install tqdm
from tqdm import tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (4.66.1)

In [4]:
from google.colab import files
import math
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import urllib.request
from gensim.models.word2vec import Word2Vec

In [5]:
recipe = pd.read_csv('TB_RECIPE_SEARCH-220701.csv', encoding='cp949', nrows=125000)

In [5]:
recipe

,RCP_SNO,RCP_TTL,CKG_NM,RGTR_ID,RGTR_NM,INQ_CNT,RCMM_CNT,SRAP_CNT,CKG_MTH_ACTO_NM,CKG_STA_ACTO_NM,CKG_MTRL_ACTO_NM,CKG_KND_ACTO_NM,CKG_IPDC,CKG_MTRL_CN,CKG_INBUN_NM,CKG_DODF_NM,CKG_TIME_NM,FIRST_REG_DT
0,128671,어묵김말이,어묵김말이,skfo0701,꽃날,9592,6,66,튀김,간식,가공식품류,디저트,맛있는 김말이에 쫄깃함을 더한 어묵 김말이예요-,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,2인분,초급,60분이내,20070402131403
1,128892,두부에 꼬리가 달렸어요!!,NaN,skfo0701,꽃날,5538,3,26,부침,일상,해물류,밑반찬,꼬리가 너-무- 매력적인 두부새우전. 두부와 야채를 한번에!! 영양까지 만점인 두부...,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,3인분,초급,30분이내,20070402205937
2,128932,입안에서 톡톡톡,NaN,skfo0701,꽃날,6802,8,36,굽기,일상,해물류,밥/죽/떡,간단하게 만들어 보는 알이 톡톡톡 알밥♥ 다 먹고 누룽지까지 싹싹 긁어먹는게 최고죠...,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,2인분,초급,30분이내,20070402224355
3,131871,★현미호두죽,현미호두죽,cds1117,햇님&별님,2912,0,9,끓이기,일상,쌀,밥/죽/떡,현미호두죽,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,2인분,초급,30분이내,20070410142301
4,139247,부들부들 보들보들 북어갈비♥,북어갈비,skfo0701,꽃날,6865,3,97,굽기,술안주,건어물류,메인반찬,오늘은 집에서 굴러다니고 쉽게 구할 수 있는 북어로 일품요리를 만들어 보았어요! 도...,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,2인분,초급,60분이내,20070501000844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,6948703,간단한 저녁메뉴 겨울반찬 시금치나물,시금치나물,limsu11,스마일로즈의건강밥상,1366,0,24,무침,일상,채소류,밑반찬,시금치를 좋아해서 두세 번에 나누어 씨를 뿌렸어요 농사 경험이 없어서 처음엔 모르...,[재료] 시금치 200g| 대파 흰 부분 10cm [데칠때 재료] 천일염 0.5숟가...,4인분,초급,10분이내,20201218073807
124996,6948704,상주곶감 곶감말이 맛있게 만드는법,곶감말,limsu11,스마일로즈의건강밥상,672,0,7,기타,명절,과일류,기타,#곶감호두말이 호두 넣고 돌돌 말아 썰어놓으면 #손님접대 나 간식으로 손색이 없는...,[재료] 곶감 10개 | 호두,4인분,초급,30분이내,20201218074602
124997,6948705,#굴요리 #무요리 #굴무밥만들기 #솥밥만들기 #솥밥으로 만드는 굴무밥!! #영양솥밥,굴무밥,kstencil,강철새잎,2071,0,14,기타,일상,해물류,밥/죽/떡,요즘 씨알이 굵은 굴을 많이 파는 계절입니다. 제철음식이기도 한 것이 바로 굴입니...,[재료] 생굴 50g| 무 6cm한토막| 쌀 3컵| 썬쪽파 1작은술 [양념간장재료]...,6인분이상,아무나,NaN,20201218075008
124998,6948706,백종원 김치찌개 저녁반찬 맛있게 만드는 법,김치찌개,limsu11,스마일로즈의건강밥상,3352,0,32,끓이기,일상,채소류,찌개,한국인들이 가장 좋아하는 #찌개 #김치찌개 된장찌개 아닌가 합니다 저도 정말 좋아...,[재료] 돼지고기 목살 250g| 신 김치1/4쪽| 물 3컵| 청양고추 1개| 홍고...,4인분,초급,30분이내,20201218075328
124999,6948707,단무지 요리 / 단무지 무침,단무지무침,62929808,요알남Mingstar,12942,0,52,무침,초스피드,가공식품류,밑반찬,무를 소금과 등겨를 혼합한 등겨소금에 절인 저장식품이다. 단무지로 할 수 있는 간단...,[재료] 단무지 150g| 고춧가루 2Ts| 매실액 1Ts| 참깨 2Ts,1인분,아무나,5분이내,20201218083020

In [6]:
recipe_1 = recipe.loc[:,['CKG_NM', 'CKG_STA_ACTO_NM', 'CKG_MTRL_CN', 'CKG_KND_ACTO_NM']]

In [4]:
recipe_1

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
0,어묵김말이,간식,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,디저트
1,NaN,일상,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,밑반찬
2,NaN,일상,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,밥/죽/떡
3,현미호두죽,일상,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,밥/죽/떡
4,북어갈비,술안주,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,메인반찬
...,...,...,...,...
124995,시금치나물,일상,[재료] 시금치 200g| 대파 흰 부분 10cm [데칠때 재료] 천일염 0.5숟가...,밑반찬
124996,곶감말,명절,[재료] 곶감 10개 | 호두,기타
124997,굴무밥,일상,[재료] 생굴 50g| 무 6cm한토막| 쌀 3컵| 썬쪽파 1작은술 [양념간장재료]...,밥/죽/떡
124998,김치찌개,일상,[재료] 돼지고기 목살 250g| 신 김치1/4쪽| 물 3컵| 청양고추 1개| 홍고...,찌개
124999,단무지무침,초스피드,[재료] 단무지 150g| 고춧가루 2Ts| 매실액 1Ts| 참깨 2Ts,밑반찬

In [7]:
recipe_1[recipe_1['CKG_NM'].isnull()]

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
1,NaN,일상,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,밑반찬
2,NaN,일상,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,밥/죽/떡
34,NaN,술안주,[재료] 닭날개 20개| 재움용 우유 1컵 [허니머스타드소스] 머스타드 1큰술| 마...,양식
50,NaN,간식,NaN,빵
65,NaN,손님접대,[재료] 한우 우둔살 400그램| 파프리카 1개| 피망 1개| 양파 큰것 1/2개|...,양식
...,...,...,...,...
123405,NaN,일상,[재료] 감자 2개| 무 1조각| 보리새우 1줌| 팽이버섯 1덩어리| 양파 1/5개...,국/탕
123406,NaN,간식,[재료] 라이스페이퍼 8장| 햄 100g| 슬라이스치즈 2장| 양파 1/2개| 계란...,퓨전
124529,NaN,일상,[재료] 중화펜 1 [양념] 돼지기름 1국자| 식용유 1국자,기타
124639,NaN,일상,[가자미 구이재료] 가자미 3마리| 식용유 약간 [무수분 돼지고기 수육재료] 돼지고...,메인반찬
124698,NaN,일상,[재료] 멸치 2줌| 건새우 1줌| 간장 1.5큰술| 참기름 1큰술| 올리고당 or...,밑반찬

In [8]:
recipe_2 = recipe_1.drop_duplicates(['CKG_NM'])

In [ ]:
recipe_2

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
0,어묵김말이,간식,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,디저트
1,NaN,일상,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,밑반찬
3,현미호두죽,일상,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,밥/죽/떡
4,북어갈비,술안주,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,메인반찬
5,토마토스파게티,일상,[재료] 파스타면 [양념] 토마토 1개| 토마토 페이스트 3T| 양파 1/2개| 다...,면/만두
...,...,...,...,...
124985,모짜치즈고구마,초스피드,[재료] 고구마 1개| 모짜렐라치즈| 꿀 맘대로,디저트
124987,크리스마스초코케이크,간식,[재료(1호 사이즈)] 1호 사이즈 초코 케이크 시트 3장| 달걀 흰자 5개_ 17...,디저트
124990,돼지김치전,술안주,[재료] 김치 1/2포기| 양파 1/2개| 애호박 1/4개| 돼지목살 200g [양...,기타
124992,검은콩바나나두부쉐이크,다이어트,[재료] 우유 200ml| 두부 1/2모| 바나나 1개| 삶은 검은콩 3t,기타
124996,곶감말,명절,[재료] 곶감 10개 | 호두,기타

In [9]:
recipe_3 = recipe_2.dropna(subset = ['CKG_NM'])
recipe_3

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
0,어묵김말이,간식,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,디저트
3,현미호두죽,일상,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,밥/죽/떡
4,북어갈비,술안주,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,메인반찬
5,토마토스파게티,일상,[재료] 파스타면 [양념] 토마토 1개| 토마토 페이스트 3T| 양파 1/2개| 다...,면/만두
6,표고버섯탕수,손님접대,[재료] 건표고버섯 9개| 오이 1/2개| 당근 1/2개| 양파 1/2개| 사과 1...,메인반찬
...,...,...,...,...
124985,모짜치즈고구마,초스피드,[재료] 고구마 1개| 모짜렐라치즈| 꿀 맘대로,디저트
124987,크리스마스초코케이크,간식,[재료(1호 사이즈)] 1호 사이즈 초코 케이크 시트 3장| 달걀 흰자 5개_ 17...,디저트
124990,돼지김치전,술안주,[재료] 김치 1/2포기| 양파 1/2개| 애호박 1/4개| 돼지목살 200g [양...,기타
124992,검은콩바나나두부쉐이크,다이어트,[재료] 우유 200ml| 두부 1/2모| 바나나 1개| 삶은 검은콩 3t,기타
124996,곶감말,명절,[재료] 곶감 10개 | 호두,기타

In [10]:
recipe_4 = recipe_3.dropna(subset = ['CKG_MTRL_CN'])
recipe_4

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
0,어묵김말이,간식,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,디저트
3,현미호두죽,일상,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,밥/죽/떡
4,북어갈비,술안주,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,메인반찬
5,토마토스파게티,일상,[재료] 파스타면 [양념] 토마토 1개| 토마토 페이스트 3T| 양파 1/2개| 다...,면/만두
6,표고버섯탕수,손님접대,[재료] 건표고버섯 9개| 오이 1/2개| 당근 1/2개| 양파 1/2개| 사과 1...,메인반찬
...,...,...,...,...
124985,모짜치즈고구마,초스피드,[재료] 고구마 1개| 모짜렐라치즈| 꿀 맘대로,디저트
124987,크리스마스초코케이크,간식,[재료(1호 사이즈)] 1호 사이즈 초코 케이크 시트 3장| 달걀 흰자 5개_ 17...,디저트
124990,돼지김치전,술안주,[재료] 김치 1/2포기| 양파 1/2개| 애호박 1/4개| 돼지목살 200g [양...,기타
124992,검은콩바나나두부쉐이크,다이어트,[재료] 우유 200ml| 두부 1/2모| 바나나 1개| 삶은 검은콩 3t,기타
124996,곶감말,명절,[재료] 곶감 10개 | 호두,기타

<<모델 학습>>

In [12]:
sentences = [recipe.split() for recipe in recipe_4['CKG_MTRL_CN']]

In [ ]:
model = Word2Vec(sentences, vector_size=200, window=8, min_count=1, workers=4)

In [56]:
model = Word2Vec(sentences, vector_size=128, window=5, min_count=5, workers=4, sg=1) #고등어->갈치 #갈치->굴비

In [102]:
model = Word2Vec(sentences, vector_size=300, window=5, min_count=1, workers=4, sg=1) #고등어->반건조오징어 #갈치->굴비

In [62]:
model = Word2Vec(sentences, vector_size=128, window=10, min_count=1, workers=4, sg=1) #고등어->삼치 #갈치->코다리

In [65]:
model = Word2Vec(sentences, vector_size=128, window=5, min_count=1, workers=4, sg=1) #고등어->반건조오징어 #갈치->동태

In [19]:
model = Word2Vec(sentences, vector_size=300, window=5, min_count=5, workers=4, sg=1) #고등어->자반고등어 #갈치->코다리

In [13]:
model = Word2Vec(sentences, vector_size=300, window=10, min_count=5, workers=4, sg=1)

In [16]:
def reorder_list(similarity_list, target_word):
    # 'target_word'와 관련된 항목을 찾음
    target_item = next((item for item in similarity_list if item[0] == target_word), None)

    # 'target_word'가 목록에 있으면 최상위로 이동
    if target_item:
        similarity_list.remove(target_item)
        similarity_list.insert(0, target_item)

    return similarity_list

def find_related_menus(model, ingredient, recipe_dataset, topn=10):
    # Word2Vec 모델을 사용하여 입력된 재료와 유사한 단어 찾기
    similar_words = model.wv.most_similar(ingredient, topn=topn)

    # 유사한 단어 목록을 재정렬
    reordered_words = reorder_list(similar_words, ingredient)

    # 유사한 단어와 연관된 메뉴명 찾기
    for word, similarity in reordered_words:
        similar_menus = recipe_dataset[recipe_dataset['CKG_MTRL_CN'].str.contains(word, case=False)]
        print(f"Similar Word: {word}, Similarity: {similarity}")
        print("Associated Menus:")
        print(similar_menus[['CKG_NM']])
        print("\n")

def find_ingredients_by_menu_name(menu_name, recipe_dataset):
    # 메뉴명을 기반으로 재료 찾기
    matched_menus = recipe_dataset[recipe_dataset['CKG_NM'].str.contains(menu_name, case=False)]
    if not matched_menus.empty:
        print(f"Ingredients for {menu_name}:")
        for index, row in matched_menus.iterrows():
            print(row['CKG_MTRL_CN'])
    else:
        print(f"No menus found for {menu_name}")

In [17]:
def find_related_menus(model, ingredient, recipe_dataset, topn=10):
    # Word2Vec 모델을 사용하여 입력된 재료와 유사한 단어 찾기
    similar_words = model.wv.most_similar(ingredient, topn=topn)

    # '갈치'가 유사 단어 목록에 없으면 목록에 추가
    if not any(word == ingredient for word, _ in similar_words):
        similar_words.append((ingredient, 1.0))

    # 유사한 단어 목록을 재정렬
    reordered_words = reorder_list(similar_words, ingredient)

    # 유사한 단어와 연관된 메뉴명 찾기
    for word, similarity in reordered_words:
        similar_menus = recipe_dataset[recipe_dataset['CKG_MTRL_CN'].str.contains(word, case=False)]
        print(f"Similar Word: {word}, Similarity: {similarity}")
        print("Associated Menus:")
        print(similar_menus[['CKG_NM']].drop_duplicates())
        print("\n")

In [19]:
find_related_menus(model, '갈치', recipe_4)

Similar Word: 갈치, Similarity: 1.0
Associated Menus:
          CKG_NM
179         갈치조림
1122        갈치찌개
2995        갈치구이
3643       무갈치조림
4623      갈치간장조림
...          ...
120506  열무김치비빔냉면
121214    어묵갈치조림
122952     다발무김치
123474  늙은호박갈치조림
124952    갈비젓갈조림

[81 rows x 1 columns]


Similar Word: 굴비, Similarity: 0.9383744597434998
Associated Menus:
            CKG_NM
298          굴비탕수육
2249           조기찜
3203          굴비조림
3471           굴비찜
13768          굴비전
14104       묵은지굴비찜
15407         굴비구이
17187         굴비튀김
18760    보리굴비고추장무침
21433         굴비찌개
21574         굴비덮밥
21975       굴비감자조림
22485           굴비
22785         보리굴비
24533         굴비밥전
24685      고추장굴비볶음
25040           튀김
27046       감자굴비조림
27175        굴비야채전
29869      중국식굴비튀김
40669         굴비손질
41275         굴비탕수
43379          굴비장
44303         굴비강정
46014       보리굴비손질
47585        굴비굽는법
47678        굴비매운탕
58559      고사리굴비조림
82687       보리굴비구이
86641       보리굴비보관
95649        부세조기찜
98695    고구마줄기굴비조림
103129      굴비오븐구이
104254       굴비무조림
112690  보리굴비고추장장아찌
118438    보리굴비누드김밥
123293      보리굴비무침


Similar Word: 민어, Similarity: 0.9204395413398743
Associated Menus:
           CKG_NM
7393         민어구이
9884        민어매운탕
13072         민어전
16892        민어탕수
19420        깐풍민어
19747   민어무청시래기조림
21183         민어찜
34728        민어조림
38508      민어콩나물찜
77609        민어튀김
87012       민어조기찜
89411          민어
90226      민어조기조림
92061     민어돼지고기찜
101069       굴마억국
106069    반건조민어구이
119452       민어술찜
120908        민어탕


Similar Word: 조기, Similarity: 0.9184540510177612
Associated Menus:
           CKG_NM
2249          조기찜
3045        대파조기찜
4612       조기양념구이
6786        조기무조림
7944         조기조림
10619        참조기찜
14386         조기전
14649      호박생선조림
19726        조기탕수
24037        조기손질
27291     고사리조기조림
31301         조기적
39441       참조기손질
48561          조기
49220      조기감자조림
51053      참조기매운탕
52496       참조기조림
54640       허브비빔밥
60441        조기구이
60908       보리굴비찜
64348       황새기젓국
74447       참조기튀김
75615       조기야채전
78460       조기구이찜
80029   고구마줄기조기조림
83260      생선양념구이
86465     고사리조기찌개
87012       민어조기찜
90958       샐러리가루
96623     파김치조기조림
98243       조기포부침
99722      단호박말랭이
100165    늙은호박손질법
100304      두부말랭이
100532      단감말랭이
102040       감껍질차
105626      적양배추차
107264    수박무말랭이차
107778   유채나물조기조림
108732      말린애호박
109049     부세조기구이
109307      참조기구이
110299     건파뿌리육수
118902      조개매운탕
122277         모과
123410       조기튀김
124696   삶은고사리조기찜


Similar Word: 코다리, Similarity: 0.9157369136810303
Associated Menus:
            CKG_NM
183        코다리양념구이
190          깐풍코다리
1885       코다리간장조림
4129       묵은지코다리찜
4423       코다리콩나물찜
4463         코다리찌개
5151         코다리강정
5352          코다리찜
8177      코다리고추장구이
8930        코다리무조림
9056         코다리구이
9817    코다리표고버섯무조림
11442        코다리손질
11543      코다리간장구이
12235    꽈리고추코다리조림
12454         코다리볼
19539      명태코다리조림
22061         코다리국
22457    코다리데리야끼조림
23192      콩나물코다리찜
24461     시래기코다리조림
24907       코다리매운탕
30407      감자코다리찌개
32019       명태코다리찜
32910     코다리새우젓찌개
34474       코다리미역국
38340            무
51242       코다리무김치
57126         코다리탕
57321         코다리전
65009     묵은지코다리조림
67625     단호박코다리조림
68325     코다리시래기조림
75607      코다리곤약조림
76336      코다리묵은지찜
78518      간장코다리조림
78676        코다리깐풍
83947      무청코다리조림
87772       코다리김치찜
91092     코다리고추장조림
94225      코다리양념조림
99003       무코다리조림
100800     코다리감자조림
107072   코다리해물콩나물찜
107495   코다리꽈리고추조림
110131  무청시래기코다리조림
110364       코다리떡찜
112077         코다리
113271      통코다리조림
115251      코다리두부찜
116777    꽈리고추코다리찜
124895  코다리감자고추장조림


Similar Word: 동태, Similarity: 0.914476215839386
Associated Menus:
         CKG_NM
173         동태전
300          버거
1137      생선커틀릿
1193       동태찌개
3512     버섯동태찌개
...         ...
107351     수제어묵
110370   뚝배기배추국
112887    동태해물찜
121710  들기름동태찌개
122899    동태해물탕

[72 rows x 1 columns]


Similar Word: 간고등어, Similarity: 0.9061083793640137
Associated Menus:
           CKG_NM
3890      고등어카레까스
7028      고등어양파조림
9538     고등어두반장조림
17797        고등어찜
50585   연근갈치고등어조림
53808     고등어버터구이
74175    고등어고사리조림
83571    고등어우거지조림
103091   간고등어무우조림
114398  고구마대고등어조림


Similar Word: 병어, Similarity: 0.9002932906150818
Associated Menus:
         CKG_NM
914       병어매운탕
8811       병어조림
11810       병어찜
48997     병어무조림
58685    병어감자조림
73967    감자병어조림
85347      병어구이
87156      병어손질
87428      병어보관
87732        병어
91167     병어회무침
101348  애호박병어조림
120649   토란병어조림
120839      병어전


Similar Word: 도루묵, Similarity: 0.8935235738754272
Associated Menus:
          CKG_NM
3673       도루묵찌개
4281       도루묵구이
17994      도루묵조림
18167      도루묵전골
50578      도루묵손질
51235        도루묵
51455      도루묵튀김
65968     도루묵무조림
70739      도루묵지짐
104737  반건조도루묵조림


Similar Word: 자반고등어, Similarity: 0.8912338018417358
Associated Menus:
           CKG_NM
3412        고갈비구이
3811      무청고등어조림
3936      자반고등어조림
4803      자반고등어튀김
5342    자반고등어감자조림
29489       깐풍고등어
42795   자반고등어스테이크
47728   묵은지자반고등어찜
73298  고등어마늘오일파스타
99717       자반고등어


Similar Word: 생선, Similarity: 0.8910424709320068
Associated Menus:
          CKG_NM
577       삼치데리야끼
613          샐러드
1137       생선커틀릿
3173      생선살튀김볼
3472     생선치즈커틀릿
...          ...
119128  생선살다시육수밥
120057   생선머리맑은탕
120558      볼락구이
121773     생선미역국
122321    생선찜표고밥

[65 rows x 1 columns]

In [41]:
find_ingredients_by_menu_name('유자휘낭시에', recipe_4)

Ingredients for 유자휘낭시에:
[필수재료] 슈가파우더 170g| 아몬드파우더 60g| 박력분 63g| 베이킹파우더 2g| 달걀흰자 170g| 무염버터 90g| 유자청 20g| 레몬즙 1T [레몬글레이즈] 레몬즙 8g| 슈가파우더 100g [토핑재료] 피스타치오 약간| 레몬제스트 약간