In [ ]:
!curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash

--2023-11-18 12:03:16--  https://www.dropbox.com/s/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.2.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.2.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz [following]
--2023-11-18 12:03:17--  https://www.dropbox.com/s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc37c88f1ea4457f38e0049da420.dl.dropboxusercontent.com/cd/0/get/CHytZeDd_KAOT2nApPiqUwoFa4ljXktXG7geiVshtdxcrmaiH8RH6o0vuo-6oE3IqGNEfB3VdTXnwnb21jSVP5T3I2zYxSqODb3jTa0Ejixk7Ljmo7vr6wNV21JdWzyxyTmlRuT-wfWjlpY78u7pPpc7/file?dl=1# [following]
--2023-11-18 12:03:17--  https://uc37c88f1ea4457f38e0049da420.dl.dropboxusercontent.com/cd/0/get/CHytZeDd_KAOT2nApPiqUwoFa4ljXktXG7geiVshtdxcrmaiH8RH6o0vuo-6oE3IqGNEfB3VdTXnwnb21jSVP5T3I2zYxSqODb3jTa0Ejixk7Ljmo7vr6wNV21JdWzyxyTmlRuT-wfWjlpY78u7pPpc7/file?dl=1
Resolving uc37c88f1ea4457f38e0049da420.dl.dropboxusercontent.com (uc37c88f1ea4457f38e0049da420.dl.dropboxusercontent.com)... 162.125.80.15, 2620:100:601f:15::a27d:90f
Connecting to uc37c88f1ea4457f38e0049da420.dl.dropboxusercontent.com (uc37c88f1ea4457f38e0049da420.dl.dropboxusercontent.com)|162.125.80.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1414979 (1.3M) [application/binary]
Saving to: ‘mecab-0.996-ko-0.9.2.tar.gz?dl=1.1’

mecab-0.996-ko-0.9. 100%[===================>]   1.35M  1.19MB/s    in 1.1s

2023-11-18 12:03:20 (1.19 MB/s) - ‘mecab-0.996-ko-0.9.2.tar.gz?dl=1.1’ saved [1414979/1414979]

mecab-0.996-ko-0.9.2/
mecab-0.996-ko-0.9.2/example/
mecab-0.996-ko-0.9.2/example/example.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.c
mecab-0.996-ko-0.9.2/example/example.c
mecab-0.996-ko-0.9.2/example/thread_test.cpp
mecab-0.996-ko-0.9.2/mecab-config.in
mecab-0.996-ko-0.9.2/man/
mecab-0.996-ko-0.9.2/man/Makefile.am
mecab-0.996-ko-0.9.2/man/mecab.1
mecab-0.996-ko-0.9.2/man/Makefile.in
mecab-0.996-ko-0.9.2/mecab.iss.in
mecab-0.996-ko-0.9.2/config.guess
mecab-0.996-ko-0.9.2/README
mecab-0.996-ko-0.9.2/COPYING
mecab-0.996-ko-0.9.2/CHANGES.md
mecab-0.996-ko-0.9.2/README.md
mecab-0.996-ko-0.9.2/INSTALL
mecab-0.996-ko-0.9.2/config.sub
mecab-0.996-ko-0.9.2/configure.in
mecab-0.996-ko-0.9.2/swig/
mecab-0.996-ko-0.9.2/swig/Makefile
mecab-0.996-ko-0.9.2/swig/version.h.in
mecab-0.996-ko-0.9.2/swig/version.h
mecab-0.996-ko-0.9.2/swig/MeCab.i
mecab-0.996-ko-0.9.2/aclocal.m4
mecab-0.996-ko-0.9.2/LGPL
mecab-0.996-ko-0.9.2/Makefile.am
mecab-0.996-ko-0.9.2/configure
mecab-0.996-ko-0.9.2/tests/
mecab-0.996-ko-0.9.2/tests/autolink/
mecab-0.996-ko-0.9.2/tests/autolink/unk.def
mecab-0.996-ko-0.9.2/tests/autolink/dicrc
mecab-0.996-ko-0.9.2/tests/autolink/dic.csv
mecab-0.996-ko-0.9.2/tests/autolink/test
mecab-0.996-ko-0.9.2/tests/autolink/char.def
mecab-0.996-ko-0.9.2/tests/autolink/matrix.def
mecab-0.996-ko-0.9.2/tests/autolink/test.gld
mecab-0.996-ko-0.9.2/tests/t9/
mecab-0.996-ko-0.9.2/tests/t9/unk.def
mecab-0.996-ko-0.9.2/tests/t9/ipadic.pl
mecab-0.996-ko-0.9.2/tests/t9/dicrc
mecab-0.996-ko-0.9.2/tests/t9/dic.csv
mecab-0.996-ko-0.9.2/tests/t9/test
mecab-0.996-ko-0.9.2/tests/t9/char.def
mecab-0.996-ko-0.9.2/tests/t9/matrix.def
mecab-0.996-ko-0.9.2/tests/t9/mkdic.pl
mecab-0.996-ko-0.9.2/tests/t9/test.gld
mecab-0.996-ko-0.9.2/tests/cost-train/
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.train
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.test
mecab-0.996-ko-0.9.2/tests/cost-train/seed/
mecab-0.996-ko-0.9.2/tests/cost-train/seed/rewrite.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/feature.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/unk.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dicrc
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dic.csv
mecab-0.996-ko-0.9.2/tests/cost-train/seed/char.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/matrix.def
mecab-0.996-ko-0.9.2/tests/run-eval.sh
mecab-0.996-ko-0.9.2/tests/run-cost-train.sh
mecab-0.996-ko-0.9.2/tests/Makefile.am
mecab-0.996-ko-0.9.2/tests/katakana/
mecab-0.996-ko-0.9.2/tests/katakana/unk.def
mecab-0.996-ko-0.9.2/tests/katakana/dicrc
mecab-0.996-ko-0.9.2/tests/katakana/dic.csv
mecab-0.996-ko-0.9.2/tests/katakana/test
mecab-0.996-ko-0.9.2/tests/katakana/char.def
mecab-0.996-ko-0.9.2/tests/katakana/matrix.def
mecab-0.996-ko-0.9.2/tests/katakana/test.gld
mecab-0.996-ko-0.9.2/tests/eval/
mecab-0.996-ko-0.9.2/tests/eval/answer
mecab-0.996-ko-0.9.2/tests/eval/system
mecab-0.996-ko-0.9.2/tests/eval/test.gld
mecab-0.996-ko-0.9.2/tests/shiin/
mecab-0.996-ko-0.9.2/tests/shiin/unk.def
mecab-0.996-ko-0.9.2/tests/shiin/dicrc
mecab-0.996-ko-0.9.2/tests/shiin/dic.csv
mecab-0.996-ko-0.9.2/tests/shiin/test
mecab-0.996-ko-0.9.2/tests/shiin/char.def
mecab-0.996-ko-0.9.2/tests/shiin/matrix.def
mecab-0.996-ko-0.9.2/tests/shiin/mkdic.pl
mecab-0.996-ko-0.9.2/tests/shiin/test.gld
mecab-0.996-ko-0.9.2/tests/latin/
mecab-0.996-ko-0.9.2/tests/latin/unk.def
mecab-0.996-ko-0.9.2/tests/latin/dicrc
mecab-0.996-ko-0.9.2/tests/latin/dic.csv
mecab-0.996-ko-0.9.2/tests/latin/test
mecab-0.996-ko-0.9.2/tests/latin/char.def
mecab-0.996-ko-0.9.2/tests/latin/matrix.def
mecab-0.996-ko-0.9.2/tests/latin/test.gld
mecab-0.996-ko-0.9.2/tests/chartype/
mecab-0.996-ko-0.9.2/tests/chartype/unk.def
mecab-0.996-ko-0.9.2/tests/chartype/dicrc
mecab-0.996-ko-0.9.2/tests/chartype/dic.csv
mecab-0.996-ko-0.9.2/tests/chartype/test
mecab-0.996-ko-0.9.2/tests/chartype/char.def
mecab-0.996-ko-0.9.2/tests/chartype/matrix.def
mecab-0.996-ko-0.9.2/tests/chartype/test.gld
mecab-0.996-ko-0.9.2/tests/run-dics.sh
mecab-0.996-ko-0.9.2/tests/ngram/
mecab-0.996-ko-0.9.2/tests/ngram/unk.def
mecab-0.996-ko-0.9.2/tests/ngram/dicrc
mecab-0.996-ko-0.9.2/tests/ngram/dic.csv
mecab-0.996-ko-0.9.2/tests/ngram/test
mecab-0.996-ko-0.9.2/tests/ngram/char.def
mecab-0.996-ko-0.9.2/tests/ngram/matrix.def
mecab-0.996-ko-0.9.2/tests/ngram/test.gld
mecab-0.996-ko-0.9.2/tests/Makefile.in
mecab-0.996-ko-0.9.2/ltmain.sh
mecab-0.996-ko-0.9.2/config.rpath
mecab-0.996-ko-0.9.2/config.h.in
mecab-0.996-ko-0.9.2/mecabrc.in
mecab-0.996-ko-0.9.2/GPL
mecab-0.996-ko-0.9.2/Makefile.train
mecab-0.996-ko-0.9.2/ChangeLog
mecab-0.996-ko-0.9.2/install-sh
mecab-0.996-ko-0.9.2/AUTHORS
mecab-0.996-ko-0.9.2/doc/
mecab-0.996-ko-0.9.2/doc/bindings.html
mecab-0.996-ko-0.9.2/doc/posid.html
mecab-0.996-ko-0.9.2/doc/unk.html
mecab-0.996-ko-0.9.2/doc/learn.html
mecab-0.996-ko-0.9.2/doc/format.html
mecab-0.996-ko-0.9.2/doc/libmecab.html
mecab-0.996-ko-0.9.2/doc/mecab.css
mecab-0.996-ko-0.9.2/doc/feature.html
mecab-0.996-ko-0.9.2/doc/Makefile.am
mecab-0.996-ko-0.9.2/doc/soft.html
mecab-0.996-ko-0.9.2/doc/en/
mecab-0.996-ko-0.9.2/doc/en/bindings.html
mecab-0.996-ko-0.9.2/doc/dic-detail.html
mecab-0.996-ko-0.9.2/doc/flow.png
mecab-0.996-ko-0.9.2/doc/mecab.html
mecab-0.996-ko-0.9.2/doc/index.html
mecab-0.996-ko-0.9.2/doc/result.png
mecab-0.996-ko-0.9.2/doc/doxygen/
mecab-0.996-ko-0.9.2/doc/doxygen/tab_a.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals_eval.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_vars.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.css
mecab-0.996-ko-0.9.2/doc/doxygen/tab_r.gif
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h_source.html
mecab-0.996-ko-0.9.2/doc/doxygen/tabs.css
mecab-0.996-ko-0.9.2/doc/doxygen/nav_f.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals.html
mecab-0.996-ko-0.9.2/doc/doxygen/nav_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/closed.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_l.gif
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/tab_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaces.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaceMeCab.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/files.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/index.html
mecab-0.996-ko-0.9.2/doc/doxygen/annotated.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_defs.html
mecab-0.996-ko-0.9.2/doc/doxygen/classes.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h-source.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.gif
mecab-0.996-ko-0.9.2/doc/doxygen/bc_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/open.png
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h.html
mecab-0.996-ko-0.9.2/doc/dic.html
mecab-0.996-ko-0.9.2/doc/partial.html
mecab-0.996-ko-0.9.2/doc/feature.png
mecab-0.996-ko-0.9.2/doc/Makefile.in
mecab-0.996-ko-0.9.2/missing
mecab-0.996-ko-0.9.2/BSD
mecab-0.996-ko-0.9.2/NEWS
mecab-0.996-ko-0.9.2/mkinstalldirs
mecab-0.996-ko-0.9.2/src/
mecab-0.996-ko-0.9.2/src/dictionary.h
mecab-0.996-ko-0.9.2/src/writer.h
mecab-0.996-ko-0.9.2/src/utils.h
mecab-0.996-ko-0.9.2/src/string_buffer.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.cpp
mecab-0.996-ko-0.9.2/src/make.bat
mecab-0.996-ko-0.9.2/src/mecab.h
mecab-0.996-ko-0.9.2/src/freelist.h
mecab-0.996-ko-0.9.2/src/string_buffer.h
mecab-0.996-ko-0.9.2/src/learner_tagger.h
mecab-0.996-ko-0.9.2/src/dictionary_compiler.cpp
mecab-0.996-ko-0.9.2/src/eval.cpp
mecab-0.996-ko-0.9.2/src/mecab-system-eval.cpp
mecab-0.996-ko-0.9.2/src/darts.h
mecab-0.996-ko-0.9.2/src/param.h
mecab-0.996-ko-0.9.2/src/char_property.h
mecab-0.996-ko-0.9.2/src/learner_node.h
mecab-0.996-ko-0.9.2/src/mecab-dict-gen.cpp
mecab-0.996-ko-0.9.2/src/mecab-dict-index.cpp
mecab-0.996-ko-0.9.2/src/winmain.h
mecab-0.996-ko-0.9.2/src/thread.h
mecab-0.996-ko-0.9.2/src/context_id.cpp
mecab-0.996-ko-0.9.2/src/Makefile.am
mecab-0.996-ko-0.9.2/src/connector.h
mecab-0.996-ko-0.9.2/src/common.h
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.cpp
mecab-0.996-ko-0.9.2/src/Makefile.msvc.in
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.h
mecab-0.996-ko-0.9.2/src/feature_index.h
mecab-0.996-ko-0.9.2/src/iconv_utils.cpp
mecab-0.996-ko-0.9.2/src/char_property.cpp
mecab-0.996-ko-0.9.2/src/mecab-test-gen.cpp
mecab-0.996-ko-0.9.2/src/tagger.cpp
mecab-0.996-ko-0.9.2/src/mecab-cost-train.cpp
mecab-0.996-ko-0.9.2/src/learner.cpp
mecab-0.996-ko-0.9.2/src/dictionary.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.cpp
mecab-0.996-ko-0.9.2/src/ucs.h
mecab-0.996-ko-0.9.2/src/writer.cpp
mecab-0.996-ko-0.9.2/src/learner_tagger.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.h
mecab-0.996-ko-0.9.2/src/libmecab.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.h
mecab-0.996-ko-0.9.2/src/mecab.cpp
mecab-0.996-ko-0.9.2/src/utils.cpp
mecab-0.996-ko-0.9.2/src/dictionary_generator.cpp
mecab-0.996-ko-0.9.2/src/param.cpp
mecab-0.996-ko-0.9.2/src/context_id.h
mecab-0.996-ko-0.9.2/src/mmap.h
mecab-0.996-ko-0.9.2/src/viterbi.h
mecab-0.996-ko-0.9.2/src/viterbi.cpp
mecab-0.996-ko-0.9.2/src/stream_wrapper.h
mecab-0.996-ko-0.9.2/src/feature_index.cpp
mecab-0.996-ko-0.9.2/src/nbest_generator.h
mecab-0.996-ko-0.9.2/src/ucstable.h
mecab-0.996-ko-0.9.2/src/nbest_generator.cpp
mecab-0.996-ko-0.9.2/src/iconv_utils.h
mecab-0.996-ko-0.9.2/src/connector.cpp
mecab-0.996-ko-0.9.2/src/Makefile.in
mecab-0.996-ko-0.9.2/src/scoped_ptr.h
mecab-0.996-ko-0.9.2/Makefile.in
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing strerror... none required
checking whether byte ordering is bigendian... no
checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for ANSI C header files... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... (cached) no
checking for string.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking for sys/types.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for sys/types.h... (cached) yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for off_t... yes
checking for size_t... yes
checking size of char... 1
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of size_t... 8
checking for size_t... (cached) yes
checking for unsigned long long int... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for main in -lstdc++... yes
checking for pthread_create in -lpthread... yes
checking for pthread_join in -lpthread... yes
checking for getenv... yes
checking for opendir... yes
checking whether make is GNU Make... yes
checking if g++ supports stl <vector> (required)... yes
checking if g++ supports stl <list> (required)... yes
checking if g++ supports stl <map> (required)... yes
checking if g++ supports stl <set> (required)... yes
checking if g++ supports stl <queue> (required)... yes
checking if g++ supports stl <functional> (required)... yes
checking if g++ supports stl <algorithm> (required)... yes
checking if g++ supports stl <string> (required)... yes
checking if g++ supports stl <iostream> (required)... yes
checking if g++ supports stl <sstream> (required)... yes
checking if g++ supports stl <fstream> (required)... yes
checking if g++ supports template <class T> (required)... yes
checking if g++ supports const_cast<> (required)... yes
checking if g++ supports static_cast<> (required)... yes
checking if g++ supports reinterpret_cast<> (required)... yes

In [ ]:
from konlpy.tag import Okt
okt = Okt()

In [ ]:
!pip install tqdm
from tqdm import tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (4.66.1)

In [ ]:
from google.colab import files
import math
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import urllib.request
from gensim.models.word2vec import Word2Vec

In [177]:
recipe = pd.read_csv('TB_RECIPE_SEARCH-220701.csv', encoding='cp949', nrows=125000)

In [178]:
recipe

,RCP_SNO,RCP_TTL,CKG_NM,RGTR_ID,RGTR_NM,INQ_CNT,RCMM_CNT,SRAP_CNT,CKG_MTH_ACTO_NM,CKG_STA_ACTO_NM,CKG_MTRL_ACTO_NM,CKG_KND_ACTO_NM,CKG_IPDC,CKG_MTRL_CN,CKG_INBUN_NM,CKG_DODF_NM,CKG_TIME_NM,FIRST_REG_DT
0,128671,어묵김말이,어묵김말이,skfo0701,꽃날,9592,6,66,튀김,간식,가공식품류,디저트,맛있는 김말이에 쫄깃함을 더한 어묵 김말이예요-,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,2인분,초급,60분이내,2.010000e+13
1,128892,두부에 꼬리가 달렸어요!!,NaN,skfo0701,꽃날,5538,3,26,부침,일상,해물류,밑반찬,꼬리가 너-무- 매력적인 두부새우전. 두부와 야채를 한번에!! 영양까지 만점인 두부...,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,3인분,초급,30분이내,2.010000e+13
2,128932,입안에서 톡톡톡,NaN,skfo0701,꽃날,6802,8,36,굽기,일상,해물류,밥/죽/떡,간단하게 만들어 보는 알이 톡톡톡 알밥♥ 다 먹고 누룽지까지 싹싹 긁어먹는게 최고죠...,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,2인분,초급,30분이내,2.010000e+13
3,131871,★현미호두죽,현미호두죽,cds1117,햇님&별님,2912,0,9,끓이기,일상,쌀,밥/죽/떡,현미호두죽,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,2인분,초급,30분이내,2.010000e+13
4,139247,부들부들 보들보들 북어갈비♥,북어갈비,skfo0701,꽃날,6865,3,97,굽기,술안주,건어물류,메인반찬,오늘은 집에서 굴러다니고 쉽게 구할 수 있는 북어로 일품요리를 만들어 보았어요! 도...,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,2인분,초급,60분이내,2.010000e+13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,6948703,간단한 저녁메뉴 겨울반찬 시금치나물,시금치나물,limsu11,스마일로즈의건강밥상,1366,0,24,무침,일상,채소류,밑반찬,시금치를 좋아해서 두세 번에 나누어 씨를 뿌렸어요 농사 경험이 없어서 처음엔 모르...,[재료] 시금치 200g| 대파 흰 부분 10cm [데칠때 재료] 천일염 0.5숟가...,4인분,초급,10분이내,2.020000e+13
124996,6948704,상주곶감 곶감말이 맛있게 만드는법,곶감말,limsu11,스마일로즈의건강밥상,672,0,7,기타,명절,과일류,기타,#곶감호두말이 호두 넣고 돌돌 말아 썰어놓으면 #손님접대 나 간식으로 손색이 없는...,[재료] 곶감 10개 | 호두,4인분,초급,30분이내,2.020000e+13
124997,6948705,#굴요리 #무요리 #굴무밥만들기 #솥밥만들기 #솥밥으로 만드는 굴무밥!! #영양솥밥,굴무밥,kstencil,강철새잎,2071,0,14,기타,일상,해물류,밥/죽/떡,요즘 씨알이 굵은 굴을 많이 파는 계절입니다. 제철음식이기도 한 것이 바로 굴입니...,[재료] 생굴 50g| 무 6cm한토막| 쌀 3컵| 썬쪽파 1작은술 [양념간장재료]...,6인분이상,아무나,NaN,2.020000e+13
124998,6948706,백종원 김치찌개 저녁반찬 맛있게 만드는 법,김치찌개,limsu11,스마일로즈의건강밥상,3352,0,32,끓이기,일상,채소류,찌개,한국인들이 가장 좋아하는 #찌개 #김치찌개 된장찌개 아닌가 합니다 저도 정말 좋아...,[재료] 돼지고기 목살 250g| 신 김치1/4쪽| 물 3컵| 청양고추 1개| 홍고...,4인분,초급,30분이내,2.020000e+13
124999,6948707,단무지 요리 / 단무지 무침,단무지무침,62929808,요알남Mingstar,12942,0,52,무침,초스피드,가공식품류,밑반찬,무를 소금과 등겨를 혼합한 등겨소금에 절인 저장식품이다. 단무지로 할 수 있는 간단...,[재료] 단무지 150g| 고춧가루 2Ts| 매실액 1Ts| 참깨 2Ts,1인분,아무나,5분이내,2.020000e+13

In [179]:
recipe_1 = recipe.loc[:,['CKG_NM', 'CKG_STA_ACTO_NM', 'CKG_MTRL_CN', 'CKG_KND_ACTO_NM']]

In [180]:
recipe_1

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
0,어묵김말이,간식,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,디저트
1,NaN,일상,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,밑반찬
2,NaN,일상,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,밥/죽/떡
3,현미호두죽,일상,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,밥/죽/떡
4,북어갈비,술안주,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,메인반찬
...,...,...,...,...
124995,시금치나물,일상,[재료] 시금치 200g| 대파 흰 부분 10cm [데칠때 재료] 천일염 0.5숟가...,밑반찬
124996,곶감말,명절,[재료] 곶감 10개 | 호두,기타
124997,굴무밥,일상,[재료] 생굴 50g| 무 6cm한토막| 쌀 3컵| 썬쪽파 1작은술 [양념간장재료]...,밥/죽/떡
124998,김치찌개,일상,[재료] 돼지고기 목살 250g| 신 김치1/4쪽| 물 3컵| 청양고추 1개| 홍고...,찌개
124999,단무지무침,초스피드,[재료] 단무지 150g| 고춧가루 2Ts| 매실액 1Ts| 참깨 2Ts,밑반찬

In [181]:
recipe_1[recipe_1['CKG_NM'].isnull()]

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
1,NaN,일상,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,밑반찬
2,NaN,일상,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,밥/죽/떡
34,NaN,술안주,[재료] 닭날개 20개| 재움용 우유 1컵 [허니머스타드소스] 머스타드 1큰술| 마...,양식
50,NaN,간식,NaN,빵
65,NaN,손님접대,[재료] 한우 우둔살 400그램| 파프리카 1개| 피망 1개| 양파 큰것 1/2개|...,양식
...,...,...,...,...
123405,NaN,일상,[재료] 감자 2개| 무 1조각| 보리새우 1줌| 팽이버섯 1덩어리| 양파 1/5개...,국/탕
123406,NaN,간식,[재료] 라이스페이퍼 8장| 햄 100g| 슬라이스치즈 2장| 양파 1/2개| 계란...,퓨전
124529,NaN,일상,[재료] 중화펜 1 [양념] 돼지기름 1국자| 식용유 1국자,기타
124639,NaN,일상,[가자미 구이재료] 가자미 3마리| 식용유 약간 [무수분 돼지고기 수육재료] 돼지고...,메인반찬
124698,NaN,일상,[재료] 멸치 2줌| 건새우 1줌| 간장 1.5큰술| 참기름 1큰술| 올리고당 or...,밑반찬

In [182]:
recipe_2 = recipe_1.drop_duplicates(['CKG_NM'])

In [183]:
recipe_2

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
0,어묵김말이,간식,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,디저트
1,NaN,일상,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,밑반찬
3,현미호두죽,일상,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,밥/죽/떡
4,북어갈비,술안주,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,메인반찬
5,토마토스파게티,일상,[재료] 파스타면 [양념] 토마토 1개| 토마토 페이스트 3T| 양파 1/2개| 다...,면/만두
...,...,...,...,...
124985,모짜치즈고구마,초스피드,[재료] 고구마 1개| 모짜렐라치즈| 꿀 맘대로,디저트
124987,크리스마스초코케이크,간식,[재료(1호 사이즈)] 1호 사이즈 초코 케이크 시트 3장| 달걀 흰자 5개_ 17...,디저트
124990,돼지김치전,술안주,[재료] 김치 1/2포기| 양파 1/2개| 애호박 1/4개| 돼지목살 200g [양...,기타
124992,검은콩바나나두부쉐이크,다이어트,[재료] 우유 200ml| 두부 1/2모| 바나나 1개| 삶은 검은콩 3t,기타
124996,곶감말,명절,[재료] 곶감 10개 | 호두,기타

In [184]:
recipe_3 = recipe_2.dropna(subset = ['CKG_NM'])
recipe_3

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
0,어묵김말이,간식,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,디저트
3,현미호두죽,일상,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,밥/죽/떡
4,북어갈비,술안주,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,메인반찬
5,토마토스파게티,일상,[재료] 파스타면 [양념] 토마토 1개| 토마토 페이스트 3T| 양파 1/2개| 다...,면/만두
6,표고버섯탕수,손님접대,[재료] 건표고버섯 9개| 오이 1/2개| 당근 1/2개| 양파 1/2개| 사과 1...,메인반찬
...,...,...,...,...
124985,모짜치즈고구마,초스피드,[재료] 고구마 1개| 모짜렐라치즈| 꿀 맘대로,디저트
124987,크리스마스초코케이크,간식,[재료(1호 사이즈)] 1호 사이즈 초코 케이크 시트 3장| 달걀 흰자 5개_ 17...,디저트
124990,돼지김치전,술안주,[재료] 김치 1/2포기| 양파 1/2개| 애호박 1/4개| 돼지목살 200g [양...,기타
124992,검은콩바나나두부쉐이크,다이어트,[재료] 우유 200ml| 두부 1/2모| 바나나 1개| 삶은 검은콩 3t,기타
124996,곶감말,명절,[재료] 곶감 10개 | 호두,기타

In [431]:
recipe_4 = recipe_3.dropna(subset = ['CKG_MTRL_CN'])
recipe_4

,CKG_NM,CKG_STA_ACTO_NM,CKG_MTRL_CN,CKG_KND_ACTO_NM
0,어묵김말이,간식,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,디저트
3,현미호두죽,일상,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,밥/죽/떡
4,북어갈비,술안주,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,메인반찬
5,토마토스파게티,일상,[재료] 파스타면 [양념] 토마토 1개| 토마토 페이스트 3T| 양파 1/2개| 다...,면/만두
6,표고버섯탕수,손님접대,[재료] 건표고버섯 9개| 오이 1/2개| 당근 1/2개| 양파 1/2개| 사과 1...,메인반찬
...,...,...,...,...
124985,모짜치즈고구마,초스피드,[재료] 고구마 1개| 모짜렐라치즈| 꿀 맘대로,디저트
124987,크리스마스초코케이크,간식,[재료(1호 사이즈)] 1호 사이즈 초코 케이크 시트 3장| 달걀 흰자 5개_ 17...,디저트
124990,돼지김치전,술안주,[재료] 김치 1/2포기| 양파 1/2개| 애호박 1/4개| 돼지목살 200g [양...,기타
124992,검은콩바나나두부쉐이크,다이어트,[재료] 우유 200ml| 두부 1/2모| 바나나 1개| 삶은 검은콩 3t,기타
124996,곶감말,명절,[재료] 곶감 10개 | 호두,기타

No charts were generated by quickchart
Warning: total number of rows (37169) exceeds max_rows (20000). Limiting to first (20000) rows.

In [186]:
print(len(recipe_4))

37169

In [432]:
# 불용어 정의
stopwords = ['|']

# 형태소 분석기 OKT를 사용한 토큰화 작업 (다소 시간 소요)
okt = Okt()

tokenized_data = []
for sentence in tqdm(recipe_4['CKG_MTRL_CN']):
    tokenized_sentence = okt.morphs(sentence, stem=True) # 토큰화
    stopwords_removed_sentence = [word for word in tokenized_sentence if not word in stopwords] # 불용어 제거
    tokenized_data.append(stopwords_removed_sentence)

100%|██████████| 37169/37169 [02:42<00:00, 228.36it/s]

In [433]:
print(tokenized_data[:100])

[['[', '재료', ']', '어묵', '2', '개', '김밥', '용김', '3', '장', '당면', '1', '움큼', '양파', '1/2', '개', '당근', '1/2', '개', '깻잎', '6', '장', '튀김', '가루', '1', '컵', '올리브유', '적당', '량', '간장', '1', 'T', '참기름', '1', 'T'], ['[', '재료', ']', '현미', '4', '컵', '찹쌀', '2', '컵', '호두', '50', 'g', '물', '1/2', '컵', '소금', '약간'], ['[', '재료', ']', '북어', '포', '1', '마리', '찹쌀', '가루', '1', 'C', '[', '양념', ']', '간장', '2', 'T', '설탕', '1', 'T', '물', '1', 'T', '다지다', '파', '1', 'T', '다지다', '마늘', '1', 'T', '참기름', '1', 'T', '깨소금', '1', 'T', '후춧가루', '약간'], ['[', '재료', ']', '파스타', '면', '[', '양념', ']', '토마토', '1', '개', '토마토', '페이스', '트', '3', 'T', '양파', '1/2', '개', '다지다', '마늘', '1', 'T', '피망', '1/2', '개', '올리브유', '3', 'T'], ['[', '재료', ']', '건', '표고버섯', '9', '개', '오이', '1/2', '개', '당근', '1/2', '개', '양파', '1/2', '개', '사과', '1/2', '쪽', '그', '외', '의', '야채', '과일', '[', '녹말', '물', ']', '녹말가루', '2', 'C', '물', '1', 'C', '계란', '노른자', '1', '개', '[', '탕수', '소스', ']', '물', '2', 'C', '설탕', '1/2', 'C', '식초', '3', 'T', '간장', '1', 'T', '녹말', '물', '2', 'T'], ['[', '재료', ']', '닭', '1', '마리', '[', '닭', '양념', ']', '통', '마늘', '3', '개', '다지다', '마늘', '1', 'T', '화이트와인', '또는', '우유', '올리브유', '또는', '버터', '마늘', '솔트', '또는', '소금', '[', '샐러드', '드레싱', ']', '파인애플', '2', '쪽', '마요네즈', '2', 'T', '머스터드', '1', 'T', '식초', '1/2', 'T', '(', '또는', '레몬', '즙', ')', '꿀', '1', 'T'], ['[', '재료', ']', '양파', '1', '개', '빵가루', '달걀', '노른자', '1', '개', '밀가루', '1', 'C', '물', '약간', '파슬리'], ['[', '재료', ']', '밥', '2', '공기', '참치', '캔', '크다', '1', '개', '양파', '다지다', '김치', '김밥', '용김', '[', '양념', ']', '고추장', '다지다', '마늘', '참기름', '맛소금', '마요네즈'], ['[', '재료', ']', '떡볶이', '떡', '150', 'g', '당근', '1/2', '개', '파', '1', '뿌리', '양파', '1/2', '개', '양배추', '1/4', '통', '어묵', '2', '장', '오징어', '새우', '조갯살', '홍합', '살', '[', '양념장', ']', '고춧가루', '2', 'T', '고추장', '1', 'T', '물엿', '1', 'T', '간장', '1', 'T', '참기름', '1', 'T', '다지다', '마늘', '1/2', 'T', '깨', '1/2', 'T', '후추', '가루', '약간'], ['[', '재료', ']', '스팸', '싱글', '1', '팩', '샌드위치', '용', '식빵', '2', '쪽', '토마토', '1', '개', '상추', '2', '쪽', '치즈', '1', '장', '[', '양념', ']', '홀', '그', '레인', '머스터드', '허니', '머스터드', '다지다', '양파'], ['[', '재료', ']', '밥', '2', '공기', '깻잎', '10', '장', '참치', '작다', '캔', '1', '개', '당근', '1/2', '개', '조미', '김', '10', '장', '[', '양념', ']', '다지다', '마늘', '1/4', 't', '개', '깨소금', '맛소금', '참기름'], ['[', '재료', ']', '새우', '10', '마리', '밥', '2', '공기', '김치', '1/4', '포기', '당근', '1/2', '개', '감자', '1/2', '개', '양파', '1/2', '개', '빵가루', '달걀', '밀가루'], ['[', '재료', ']', '밥', '2', '공기', '상추', '(', '작다', '걸', '로', '골', '라서', ')', '나', '그', '외쌈', '야채', '스팸', '밑반찬', '[', '양념', ']', '참기름', '1/2', 't', '맛소금', '약간', '깨', '약간'], ['[', '재료', ']', '밥', '1', '공기', '김치', '1/6', '포기', '베이컨', '적당', '량', '깻잎', '5', '장', '양파', '1/4', '개'], ['[', '재료', ']', '식빵', '4', '장', '스팸', '1/3', '캔', '오이', '1', '개', '체다', '치즈', '(', '노랗다', '치즈', ')', '[', '양념', ']', '머스터드', '피클', '마요네즈'], ['[', '재료', ']', '고구마', '크다', '2', '개', '모차렐라', '치즈', '(', '피자치즈', ')', '1/2', '개', '버터', '1', 'T', '밀가루', '빵가루', '달걀', '1', '개'], ['[', '재료', ']', '오징어', '1', '마리', '양파', '1/4', '개', '대파', '1/2', '쪽', '당근', '1/3', '개', '청', '고추', '1', '개', '홍', '고추', '1', '개', '[', '양념', ']', '고추장', '1', 'T', '고춧가루', '1', 'T', '다지다', '마늘', '1', 'T', '참기름', '1', 'T', '설탕', '1', 't', '간장', '1', 't', '청주', '1', 't', '후추', '약간', '소금', '약간'], ['[', '재료', ']', '가래떡', '1', '개', '호두', '15', '알', '정도', '[', '양념', ']', '깨', '3', 'T', '꿀', '5', 'T'], ['[', '재료', ']', '새우', '7', '마리', '양파', '1/4', '개', '김치', '1/6', '포기', '밥', '지다', '쌀', '김밥', '용김', '계란', '밀가루', '빵가루', '[', '양념', ']', '백세', '카레', '가루', '2', 'T'], ['[', '재료', ']', '블루베리', '500', 'g', '설탕', '150', 'g', '레몬', '즙', '2', 'T', '럼', '1', 'T', '모닝', '빵', '3', '개'], ['[', '재료', ']', '모닝', '빵', '3', '개', '새우', '10', '마리', '상추', '3', '장', '토마토', '1', '개', '피클', '약간', '마요네즈', '[', '패티', '양념', ']', '다지다', '양파', '1/2', '개', '빵가루', '밀가루', '계란', '소금', '후추'], ['[', '재료', ']', '고구마', '으', '깨다', '250', 'g', '생크림', '2', '크다', '술', '설탕', '1', '크다', '술', '버터', '1', '크다', '술', '아몬드', '슬', '라이스', '모짜렐라', '치즈', '[', '커스타드', '크림', ']', '우유', '270', 'ml', '박력', '분', '25', 'g', '노른자', '3', '개', '설탕', '60', 'g', '바닐라', '오일', '약간', '버터', '20', 'g'], ['[', '재료', ']', '국내', '산', '제빵', '용', '쌀', '가루', '390', '그램', '계란', '1', '개', '우유', '250~270', 'ml', '인스턴트', '드라이', '이스트', '4', '그램', '소금', '4', '그램', '버터', '50', '그램', '설탕', '50', '그램', '밤', '조림', '150', '그램', '아몬드', '슬', '라이스', '30', '그램', '.', '[', '쿠키', '반죽', ']', '버터', '75', '그램', '설탕', '75', '그램', '노른자', '1', '개', '박력', '분', '110', '그램', '바닐라', '오일', '약간'], ['[', '재료', ']', '고구마', '5', '개', '생크림', '3', '크다', '술', '버터', '2', '크다', '술', '커스타드', '크림', '100', 'g', '설탕', '1', '크다', '술', '소금', '약간', '소금', '약간', '설탕', '1', '크다', '술'], ['[', '재료', ']', '감자', '(', '中', ')', '2', '개', '생크림', '1', 'C', '우유', '1', 'C', '양파', '1/2', '개', '베이컨', '2', '장', '체다', '치즈', '1', '장', '피자치즈', '약간', '[', '양념', ']', '버터', '1', 'T', '육수', '1', 'C'], ['[', '재료', ']', '좋아하다', '종류', '의', '라면', '1', '봉지', '김치', '1/4', '포기', '굴', '5~6', '개', '파', '1', '개', '청', 'or', '홍', '고추', '1', '개', '[', '양념', ']', '고춧가루', '약간'], ['[', '재료', ']', '감자', '4', '개', '올리브유', '약간', '베이컨', '4', '장', '모짜렐라', '치즈', '200', '그램', '파슬리', '약간', '[', '양념', ']', '소금', '약간'], ['[', '재료', ']', '양배추', '1/2', '통', '숙주', '1', '줌', '오징어', '1', '마리', '새우', '6', '마리', '베이컨', '2', '줄', '계란', '1', '개', '실파', '약간', '[', '오코노미야키', '반죽', ']', '밀가루', '1', 'C', '물', '1', 'C', '혼다', '시', '1', 'T', '후추', '&', '소금', '약간', '[', '양념', ']', '돈가스', '소스', '마요네즈'], ['[', '재료', ']', '당면', '2', '줌', '부추', '1', '줌', '만', '두피', '10', '장', '[', '양념', ']', '간장', '2', 'T', '물엿', '또는', '설탕', '1', 'T', '참기름', '1', 'T', '다지다', '파', '1', 'T', '다지다', '마늘', '1', 'T', '소금', '약간', '후추', '약간'], ['[', '재료', ']', '손', '두부', '1', '모', '포도', '씨유', '소금', '약간', '꽈리', '고추', '1', '줌', '양파', '1/2', '개', '대파', '1', '줄기', '[', '양념장', ']', '간장', '70', 'ml', '물', '300', 'ml', '설탕', '1', '크다', '술', '물엿', 'or', '요리', '당', '1', '크다', '술', '굴소스', '1', '크다', '술', '고춧가루', '2', '크다', '술', '마늘', '1/2', '크다', '술', '후춧가루', '1', '작다', '술'], ['[', '재료', ']', '갈비', '900', '그램', '월계수', '잎', '3', '장', '통', '마늘', '7', '쪽', '후춧가루', '1/2', '크다', '술', '청주', '1', '크다', '술', '감자', '2', '개', '양파', '1', '개', '[', '양념', ']', '고춧가루', '1', '컵', '(', '대략', '8', '크다', '술', ')|', '간장', '1', '컵', '(', '8', '크다', '술', ')|', '청량고추', '3', '개', '통', '마늘', '10', '개', '청주', '3', '크다', '술', '설탕', '3', '크다', '술', '생강', '가루', '1/2', '크다', '술', '참기름', '1', '+', '1/2', '크다', '술', '양파', '1', '개', '파인애플', '2', '쪽', '양', '겨자', '가루', '3', '크다', '술'], ['[', '재료', ']', '어묵', '500', 'g', '포도', '씨유', '적당', '량', '꽈리', '고추', '1', '줌', '양파', '1/2', '개', '느타리버섯', '1', '줌', '대파', '1', '줄기', '물', '1/4', '컵', '[', '양념', ']', '간장', '70', 'ml', '물', '30', 'ml', '설탕', '1', '크다', '술', '물엿', '2', '크다', '술', '굴소스', '1', '크다', '술', '고춧가루', '1', '크다', '술', '마늘', '1/2', '크다', '술', '후춧가루', '1', '작다', '술', '통깨', '약간'], ['[', '재료', ']', '밥', '2', '공기', '김밥', '용어', '묵', '오이', '1/2', '개', '캔햄', '이나', '김밥', '용햄', '김밥', '용', '단무지', '김', '[', '양념', ']', '참기름', '1', 'T', '맛소금', '1', 'T'], ['[', '재료', ']', '홍시', '또는', '대', '봉시', '크다', '6~7', '개', '생크림', '300', '그램', '[', '양념', ']', '설탕', '또는', '꿀', '3', '크다', '술', '레몬', '즙', '1', '크다', '술'], ['[', '재료', ']', '박력', '분', '210', '그램', '단호박', '가루', '45', '그램', '버터', '180', '그램', '슈가', '파우더', '78', '그램', '호박', '씨', '50', '그램', '바닐라', '오일', '약간', '계란', '흰자', '약간', '설탕', '약간'], ['[', '재료', ']', '박력', '분', '250', '그램', '버터', '135', '그램', '베이', '킹', '파우더', '4', '그램', '베이', '킹', '소', '다', '2', '그램', '계란', '1', '개', '설탕', '125', '그램', '초코', '칩', '200', '그램', '유기농', '초코', '뮈슬리', '100~150', '그램'], ['[', '타르트', '지', '재료', ']', '버터', '70', 'g', '박력', '분', '130', 'g', '소금', '1', 'g', '설탕', '5', 'g', '계란', '1', '개', '[', '아몬드', '크림', ']', '버터', '40', 'g', '크림', '치즈', '40', 'g', '설탕', '60', 'g', '생크림', '20', 'g', '계란', '1', '개', '아몬드', '가루', '120', 'g', '코코넛', '가루', '30', 'g', '바닐라', '오일', '1', 'ts', '럼주', '1', 'Ts', '견과류', '적당', '량'], ['[', '재료', ']', '홍시', '크다', '4~5', '개', '[', '양념', ']', '설탕', '4~5', '크다', '술', '레몬', '즙', '1', '크다', '술', '플레인', '요거트', '1000', 'ml'], ['[', '재료', ']', '강력', '분', '600', '그램', '우유', '250', '그램', '인', '스턴', '드', '드라이', '이스트', '16', '그램', '소금', '9', '그램', '설탕', '108', '그램', '레몬', '즙', '1', '크다', '술', '버터', '120', '그램', '계란', '2', '개', '꿀', '12', '그램', '각종', '당', '절임', '과일', '240', '그램', '럼주', '1', '컵', '정도', '토핑용', '버터', '약간'], ['[', '재료', ']', '배추김치', '50', 'g', '김밥', '속', '에', '넣다', '소고기', '50', 'g', '체다', '치즈', '1', '장', '스파게티', '국수', '1', '인분', '모짜렐라', '치즈', '적당', '량', '[', '양념', ']', '헤비', '위핑크림', '150', 'g'], ['[', '재료', ']', '돼지고기', '아무', '부위', '나', '200', 'g', '감자', '중간', '크기', '1', '개', '양파', '1/2', '개', '두부', '1/2', '모', '[', '양념', ']', '고추장', '3', '크다', '술', '된장', '1', '크다', '술', '물', '마늘', '다지다', '1', '크다', '술', '참기름', '1', '작다', '술'], ['[', '재료', ']', '박력', '분', '250', '그램', '버터', '100', '그램', '설탕', '80', '그램', '밤', '페이스', '트', '70', '그램', '장식', '용', '밤', '조림', '6', '개', '베이킹파우더', '2', 'ts', '계란', '2', '개', '우유', '120', 'ml', '밤', '조림', '150', '그램', '바닐라', '오일', '약간'], ['[', '재료', ']', '닭', '중간', '크기', '1', '마리', '청양고추', '5', '개', '건', '고추', '5', '개', '양파', '1', '개', '감자', '3', '개', '당면', '1', '줌', '대파', '2', '줄기', '물', '1', '컵', '[', '닭', '밑', '간', ']', '생강', '즙', '1', '크다', '술', '후춧가루', '1/2', '크다', '술', '마늘', '1/2', '크다', '술', '청주', '1', '크다', '술', '[', '양념장', ']', '설탕', '3', '+', '1/2', '크다', '술', '간장', '110', 'ml', '캬라멜', '소스', '1/2', '크다', '술', '청양고추', '5', '개', '후춧가루', '1/2', '크다', '술', '다지다', '마늘', '1/2', '크다', '술', '참기름', '1', '크다', '술'], ['[', '재료', ']', '브리', '오슈', '슬', '라이스', '(', '약간', '두', '툼', '하', '게', ')', '2', '장', '바나나', '1/2', '개', '계란', '1', '개', '우유', '1', 'TBSP', '버터', '조금', '베이컨', '4', '장', '좋아하다', '과일', '[', '양념', ']', '소금', '1', '꼬집다', '시럽', '적당', '량', '슈거', '파우더', '적당', '량'], ['[', '재료', ']', '단호박', '작다', '크기', '1', '통', '낙지', '작다', '크기', '1', '마리', '모', '듬', '해물', '1', '줌', '칵테일', '새우', '1', '줌', '양파', '작다', '크기', '1/2', '개', '파프리카', '1/2', '개', '대파', '1', '줄기', '떡볶이', '떡', '1', '줌', '피자', '피즈', '200', 'g', '[', '양념장', ']', '고추장', '2', '+', '1/2', '크다', '술', '고춧가루', '1/2', '크다', '술', '굴소스', '2', '크다', '술', '다지다', '마늘', '1', '작다', '술', '후춧가루', '1', '작다', '술', '설탕', '1/2', '크다', '술', '요리', '당', '1', '크다', '술'], ['[', '재료', ']', '앤젤', '헤어', '파스타', '1', '인분', '명란', '2', '개', '마늘', '다지다', '1', '크다', '술', '우메보시', '1', '개', '[', '양념', ']', '참기름', '2', '크다', '술', '시', '칠', '밉다', '적당', '량'], ['[', '재료', ']', '박력', '분', '40', 'g', '코코아', '가루', '50', 'g', '다크', '초콜릿', '100', 'g', '버터', '90', 'g', '달걀', '4', '개', '설탕', '120', '개', '생크림', '60', 'g', '[', '데코', '레이', '션', ']', '슈가', '파우더', '생크림'], ['[', '재료', ']', '바질', '잎', '50', 'g', '통', '마늘', '1', '쪽', '잣', '20', '개', '올리브오일', '180', 'ml', '파', '마산', '치즈', '25', 'g'], ['[', '재료', ']', '강력', '분', '500', '그램', '설탕', '10', '그램', '소금', '10', '그램', '몰트', '1', '그램', '양파', '중간', '것', '1', '개', '올리브', '20', '개', '이상', '올리브유', '60', 'cc', '물', '350', 'cc', '드라이', '이스트', '8', '그램', '(', '올리브유', '약간', ')'], ['[', '재료', ']', '흑', '밉다', '가루', '120', 'g', '노른자', '2', '개', '설탕', '1', '크다', '술', '소금', '1/3', '작다', '술', '바닐라', '오일', '약간', '베이', '킹', '파우더', '1', '작다', '술', '우유', '100', 'ml', '버터', '60', 'g', '흰자', '2', '개', '설탕', '1', '크다', '술'], ['[', '재료', ']', '후', '랑', '크다', '소세지', '(', '줄줄이', '비엔나', ')', '10', '개', '파프리카', '1', '+', '1/2', '개', '양파', '크다', '1', '개', '당근', '1/2', '개', '대파', '1', '줄기', '올리브유', '적당', '량', '[', '양념', ']', '굴소스', '1', '크다', '술', '케찹', '10', '크다', '술', '설탕', '1/2', '크다', '술', '후춧가루', '약간'], ['[', '재료', ']', '식빵', '6', '장', '양상추', '4', '쪽', '슬', '라이스', '햄', '토마토', '양', '겨자', '마요네즈', '후추', '약간', '레몬', '즙', '크림', '치즈', '계란', '6', '개', '다지다', '양파', '1', '개', '분'], ['[', '푸딩', '액', '재료', ']', '우유', '300', 'g', '설탕', '60', 'g', '계란', '3', '개', '바닐라', '오일', '2', '방울', '[', '카라멜', '소스', ']', '설탕', '60', 'g', '물', '4', '크다', '술'], ['[', '재료', ']', '감자', '중간', '것', '4', '개', '[', '양념', ']', '올리브유', '(', 'or', '카', '놀라다', '유', ')', '2', '크다', '술', '소금', '1', '작다', '술', '후춧가루', '약간', '파슬리', '가루', '약간', '다지다', '마늘', '1/2', '크다', '술', '[', '소스', ']', '사워크림', '케첩', '살사소스', '치즈', '소스'], ['[', '재료', ']', '강력', '분', '150', '그램', '박력', '분', '150', '그램', '설탕', '20', '그램', '소금', '2', '그램', '베이', '킹', '파우더', '5', '그램', '버터', '45', '그램', '건포도', '6', '그램', '달', '갈다', '1', '개', '우유', '100', 'ml', '대추야자', '씨', '빼다', '70', '그램', '계란', '물', '약간'], ['[', '재료', ']', '떡볶이', '떡', '400~500', '그램', '정도', '양파', '1/2', '개', '양배추', '크다', '1/8', '통', '대파', '2', '줄기', '어묵', '2', '장', '쫄면', '200', '그램', '정도', '물', '또는', '육수', '1', '+', '1/2', '컵', '[', '양념', ']', '다', '*', '다', '(', '소고기', '맛', '조미료', ')', '1/2', '크다', '술', '춘장', '2', '크다', '술', '고추장', '1', '크다', '술', '설탕', '2', '크다', '술', '다지다', '마늘', '1', '크다', '술'], ['[', '재료', ']', '찹쌀', '가루', '(', '습', '식', ')', '400', '그램', '찬물', '220', '그램', '바나나', '중간', '것', '2', '개', '옥수수', '전분', '적당', '량', '[', '양념', ']', '팥', '앙금', '500', '그램'], ['[', '재료', ']', '어묵', '1', '팩', '팽이버섯', '2', '봉지', '쑥갓', '약간', '당근', '1/2', '개', '표고버섯', '2', '개', '대파', '1', '쪽', '[', '카레', '육수', ']', '물', '3', '컵', '백', '세', '카레', '가루', '2', 'T', '가쓰오부시', '장국', '4', 'T'], ['[', '재료', ']', '박력', '분', '200', 'g', '버터', '160', 'g', '설탕', '160', 'g', '베이킹파우더', '1', 'T', '계란', '3', '개', '우유', '2', 'T', '초코', '칩', '40', 'g', '[', '양념', ']', '커피', '액', '기', '스', '2', 'T', '소금', '약간'], ['[', '재료', ']', '박력', '분', '250', 'g', '물', '160', 'g', '말리다', '표고버섯', '5', '개', '이스트', '5', 'g', '[', '양념', ']', '설탕', '1', 'T', '소금', '1', 'T', '간장', '1', 'T', '참기름', '1', 'T', '올리브오일', '약간'], ['[', '재료', ']', '어묵', '1', '봉지', '양배추', '1/4', '통', '[', '육수', '재료', ']', '무', '1/3', '개', '파', '1', '뿌리', '양파', '1/2', '개', '건', '새우', '약간', '다시마', '약간', '청양고추', '2', '개', '[', '양념', ']', '고춧가루', '3', 'T', '고추장', '2', 'T', '간장', '2', 'T', '설탕', '1', 'T', '물엿', '1', 'T', '다지다', '마늘', '1', 'T', '청주', '1', 'T', '후추', '가루', '약간'], ['[', '재료', ']', '홍합', '베이컨', '2', '줄', '양파', '1/2', '개', '파프리카', '1/4', '개', '파슬리', '[', '양념', ']', '생크림', '2', '컵', '좋아하다', '치즈'], ['[', '재료', ']', '강력', '분', '500', '그램', '몰트', '1', '그램', '인스턴트', '드라이', '이스트', '8', '그램', '카', '놀라다', '유', '라이트', '60', 'CC', '미지근하다', '물', '330', 'cc', '소금', '6', '그램', '설탕', '10', '그램'], ['[', '재료', ']', '우유', '1000', 'ml', '생크림', '500', 'ml', '[', '양념', ']', '레몬', '즙', '(', '1', '개', '분', ')', '6', '크다', '술', '소금', '1/2', '~', '1', '스푼'], ['[', '재료', ']', '생크림', '130', '그램', '박력', '분', '100', '그램', '설탕', '130', '그램', '베이킹파우더', '1', 'ts', '계란', '1', '개', '[', '양념', ']', '포피', '씨드', '20', '그램', '레몬', '필', '50', '그램', '유자청', '30', '그램'], ['[', '재료', ']', '박력', '분', '100', '그람', '버터', '70', '그람', '바닐라', '오일', '1~2', '방울', '아몬드', '파우더', '20', '그람', '소금', '1/4', 'ts', '슈가', '파우더', '30', '그람', '베이킹파우더', '1/4', 'ts', '시나몬', '파우더', '1/2', 'ts', '[', '양념', ']', '장식', '용', '슈가', '파우더', '1', '컵'], ['[', '재료', ']', '바나나', '으', '깨다', '3', '개', '토핑용', '바나나', '2', '개', '버터', '200', '그램', '설탕', '200', '그램', '박력', '분', '370', '그램', '코코아', '가루', '30', '그램', '초코', '칩', '50', '그램', '베이', '킹', '파우더', '1', 'ts', '베이', '킹소', '다', '1', 'ts', '생크림', '200', 'ml', '바닐라', '오일', '약간'], ['[', '재료', ']', '박력', '분', '285', '그램', '버터', '88', '그램', '계란', '3', '개', '설탕', '180', '그램', '애호박', '160', '그램', '우유', '3~5', '크다', '술', '사워크림', '250', '그램', '베이', '킹', '파우더', '4', '그램', '소금', '4', '그램', '바닐라', '오일', '약간', '[', '스트로', '이', '젤', ']|', '박력', '80', '그램', '버터', '40', '그램', '설탕', '40', '그램'], ['[', '재료', ']', '백미', '가루', '75', 'g', '아몬드', '가루', '72', 'g', '슈가', '파우더', '180', 'g', '베이', '킹', '파우더', '2', 'g', '바닐라', '가루', '2', 'g', '계란', '흰자', '200', 'g', '트리', '몰리다', '(', '물엿', ')', '18', 'g', '버터', '110', 'g'], ['[', '재료', ']', '유기농', '뮈슬리', '250', 'g', '버터', '25', 'g', '요리', '당', '50', 'g', '꿀', '50', 'g', '호박', '씨', '50', 'g'], ['[', '재료', ']', '현미', '가루', '80', 'g', '노른자', '4', '개', '설탕', '40', 'g', '우유', '또는', '물', '60', 'ml', '말차', '가루', '7~8', 'g', '포피', '시드', '10~15', 'g', '흰자', '4', '개', '설탕', '40', 'g', '카', '놀라다', '유', '또는', '녹', '인버터', '55', 'g'], ['[', '재료', ']', '돼지고기', '당근', '감자', '파프리카', '양파', '올리브유', '[', '양념', ']', '시', '즈', '닝', '솔트', '후춧가루', '파키스탄', '카레', '한국', '카레', '일본', '카레'], ['[', '재료', ']', '닭', '가슴', '살', '4', '쪽', '각종', '야채', '[', '또띠아', '재료', ']', '홍', '피망', '1/2', '개', '청', '피망', '1/2', '개', '양파', '1/2', '개', '청량고추', '3', '개', '또띠아', '8', '장', '스위트콘', '5~6', '크다', '술', '올리브유', '적당', '량', '피자치즈', '넉넉하다', '[', '또띠아', '양념', ']', '칠리소스', '적당', '량', '[', '야채', '밑', '간', ']', '시', '즈', '닝', '솔트', '1', '작다', '술', '굴소스', '1', '작다', '술', '[', '불닭', '양념', ']', '고추장', '3', '크다', '술', '고춧가루', '2', '크다', '술', '고추기름', '1/2', '크다', '술', '후춧가루', '1/2', '크다', '술', '칠리소스', '1', '크다', '술', '다지다', '마늘', '1', '크다', '술', '굴소스', '3/4', '크다', '술', '설탕', '1/2', '크다', '술', '[', '닭', '밑', '간', ']', '청주', '1', '크다', '술', '시', '즈', '닝', '솔트', '2/4', '크다', '술', '생강', '즙', '1/2', '크다', '술'], ['[', '재료', ']', '핫케이크', '가루', '300', 'g', '우유', '180~200', 'ml', '슬', '라이스', '치즈', '2', '장', '파슬리', '가루', '약간', '달걀', '3', '개', '메추리', '알', '12', '개', '[', '양념', ']', '마요네즈', '소금', '후추', '설탕'], ['[', '수제비', '반죽', ']', '중력', '분', '500', '그람', '찬물', '300', '그람', '올리브유', '2', '크다', '술', '소금', '1', '작다', '술', '양파', '1/2', '개', '호박', '1/4', '개', '감자', '크다', '2', '개', '대파', '1', '줄기', '청량고추', '3~4', '개', '다지다', '마늘', '1', '크다', '술', '참치', '캔', '작다', '1', '개', '느타리버섯', '약간', '물', '3.5', '컵', '[', '양념', ']', '고추장', '3', '크다', '술', '혼다', '시', '1', '작다', '술', '후추', '1', '작다', '술', '고춧가루', '3', '크다', '술'], ['[', '재료', ']', '루프', '유기농', '통밀', '브레드', '믹스', '1', '봉지', '우유', '330', 'ml', '카', '놀라다', '유', '1', '크다', '술', '[', '시나몬롤', '아이싱', ']', '크림', '치즈', '85', '그램', '버터', '1/4', '컵', '슈가', '파우더', '1/4', '컵', '바닐라', '오일', '약간', '[', '시나몬롤', '필링', ']', '황', '설탕', '또는', '흑설탕', '100', '그램', '시나몬', '가루', '1', '크다', '술', '땅콩', '분', '태', '1', '줌'], ['[', '재료', ']', '오이', '1', '개', '[', '양념', ']', '소금', '1', '작다', '술', '대파', '다지다', '1', '크다', '술', '마늘', '1', '작다', '술', '고추장', '1', '작다', '술', '고춧가루', '1', '작다', '술', '설탕', '1', '작다', '술', '깨소금', '1', '작다', '술', '식초', '1', '작다', '술', '참기름', '1', '작다', '술', '통깨', '조금'], ['[', '재료', ']', '강력', '분', '200', 'g', '박력', '분', '100', 'g', '우유', '100', 'g', '물', '100', 'g', '설탕', '30', 'g', '버터', '30', 'g', '인스턴트', '이스트', '4', 'g', '소금', '3', 'g', '녹차', '가루', '1', 'ts', '따다', '한', '물', '1', '크다', '술', '적', '고구마', '1', 'Ts', '딸기', '쥬스', '가루', '1', 'ts', '물', '1', '크다', '술'], ['[', '재료', ']', '초콜렛', '100', 'g', '버터', '60', 'g', '박력', '분', '20', 'g', '코코아파우더', '40', 'g', '노른자', '60', 'g', '설탕', '40', 'g', '생크림', '50', 'g', '오렌지', '술', '2', 'T', '오렌지', '제스', '트', '2', 'ts', '다크', '초코렛', '150', 'g', '건조', '딸기', '조금', '피스타치오', '조금', '[', '머랭', ']', '흰자', '120', 'g', '설탕', '50', 'g'], ['[', '재료', ']', '딸기', '10', '개', '녹말가루', '1/2', '컵', '팥소', '200', 'g', '찹쌀', '가루', '100', 'g', '물', '180', 'cc', '설탕', '50', 'g'], ['[', '재료', ']', '닭고기', '안심', '살', '12', '매', '베이비', '채소', '30', 'g', '파프리카', '조금', '식빵', '2', '장', '[', '식빵', '소스', ']', '허브', '솔트', '1/2', '크다', '술', '올리브유', '2', '크다', '술', '머스터드', '1/2', '크다', '술', '꿀', '1', '크다', '술', '바베큐', '소스', '5~7', '크다', '술', '[', '샐러드', '드레싱', ']', '올리브오일', '1', 'T', '식초', '1', 'T', '꿀', '1', 'T', '소금', '1/2', 'T', '후추', '조금', '오렌지', '쥬스', '2', 'T'], ['[', '재료', ']', '떡볶이', '떡', '400', 'g', '어묵', '2', '장', '양파', '작다', '1', '개', '양배추', '조금', '깻잎', '1', '묶음', '물국', '대접', '2', '개', '[', '양념', ']', '고추장', '1', '크다', '술', '고추', '가루', '1', '크다', '술', '찹쌀', '엿', '2', '크다', '술', '다시다', '조금', '소금', '1/2', '크다', '술'], ['[', '재료', ']', '또띠아', '2', '장', '훈제', '연어', '100', 'g', '양파', '1/4', '개', '오이', '1/2', '개', '상추', '4', '장', '오렌지', '1', '개', '마요네즈', '2', '크다', '술', '케이', '퍼', '10', '알'], ['[', '재료', ']', '밥', '2', '공기', '김치', '1', '포기', '어묵', '3', '장', '계란', '2', '개', '파슬리', '약간', '[', '양념', ']', '설탕', '1/2', '크다', '술', '굴소스', '1', '크다', '술', '통깨', '약간', '들기름', '2.5', '크다', '술'], ['[', '재료', ']', '바나나', '작다', '2', '개', '버터', '50', 'g', '박력', '분', '70', 'g', '설탕', '30', 'g', '계란', '1', '개', '베이킹파우더', '1', 'ts', '물엿', '40', 'g', '꿀', '40', 'g', '캬라멜', '소스', '20', 'g', '럼주', '1', 'Ts', '코코넛', '슬', '라이스', '조금', '[', '캬라멜', ']', '설탕', '50', 'g', '물', '1', '크다', '술'], ['[', '재료', ']', '다시마', '가다', '이포', '모밀', '면', '김', '대파

In [434]:
from konlpy.tag import Okt

# 불용어 정의
stop_words = set("[ ] | / \n".split(' '))

# Okt 객체 생성
okt = Okt()

# CKG_NM 칼럼에 대해 불용어 제거 수행
recipe_4['CKG_MTRL_CN'] = recipe_4['CKG_MTRL_CN'].apply(lambda x: ' '.join([word for word in okt.morphs(x) if word not in stop_words]))

# 불용어 제거 후 CKG_NM 칼럼 출력
print(recipe_4['CKG_MTRL_CN'])

0         재료 어묵 2 개 김밥 용김 3 장 당면 1 움큼 양파 1/2 개 당근 1/2 개 ...
3                    재료 현미 4 컵 찹쌀 2 컵 호두 50 g 물 1/2 컵 소금 약간
4         재료 북어 포 1 마리 찹쌀 가루 1 C 양념 간장 2 T 설탕 1 T 물 1 T ...
5         재료 파스타 면 양념 토마토 1 개 토마토 페이스 트 3 T 양파 1/2 개 다진 ...
6         재료 건 표고버섯 9 개 오이 1/2 개 당근 1/2 개 양파 1/2 개 사과 1/...
                                ...
124985                             재료 고구마 1 개 모짜렐라 치즈 꿀 맘대로
124987    재료 ( 1 호 사이즈 )] 1 호 사이즈 초코 케이크 시트 3 장 달걀 흰자 5 ...
124990    재료 김치 1/2 포기 양파 1/2 개 애호박 1/4 개 돼지 목살 200 g 양념...
124992            재료 우유 200 ml 두부 1/2 모 바나나 1 개 삶은 검은 콩 3 t
124996                                        재료 곶감 10 개 호두
Name: CKG_MTRL_CN, Length: 37169, dtype: object

In [190]:
from gensim.models import Word2Vec
model = Word2Vec(sentences = tokenized_data, window = 5, min_count = 5, workers = 4, sg = 0)
print('완성된 임베딩 매트릭스의 크기 확인 :', model.wv.vectors.shape)

완성된 임베딩 매트릭스의 크기 확인 : (3194, 100)

<<모델 학습>>

In [191]:
sentences = [recipe.split() for recipe in recipe_4['CKG_MTRL_CN']]
model = Word2Vec(sentences, vector_size=200, window=8, min_count=1, workers=4)

In [192]:
model = Word2Vec(sentences, vector_size=128, window=5, min_count=5, workers=4, sg=1)

In [193]:
model = Word2Vec(sentences, vector_size=300, window=5, min_count=1, workers=4, sg=1)

In [194]:
model = Word2Vec(sentences, vector_size=128, window=10, min_count=1, workers=4, sg=1)

In [195]:
model = Word2Vec(sentences, vector_size=128, window=5, min_count=1, workers=4, sg=1)

In [196]:
from gensim.models import Word2Vec

# sentences: 학습 데이터 (리스트 형태의 토큰화된 문장들)
# vector_size: 단어 벡터의 차원 수
# window: 문맥 윈도우 크기
# min_count: 최소 단어 빈도
# workers: 학습에 사용되는 CPU 스레드 수
# sg: Skip-gram 모델 사용 여부 (sg=1: 사용, sg=0: CBOW 모델 사용)
# negative: 부정적 예제의 수
# epochs: 학습 반복 횟수
model = Word2Vec(sentences, vector_size=128, window=5, min_count=5, workers=4, sg=1, negative=5, epochs=100)

In [197]:
print(model.wv.most_similar("어묵"))

[('사각', 0.7146353721618652), ('오뎅', 0.6806772351264954), ('구멍', 0.5320094227790833), ('부산', 0.5298781394958496), ('뚫린', 0.5258014798164368), ('깻잎', 0.5036743879318237), ('당면', 0.4960436522960663), ('떡', 0.4817240536212921), ('납작', 0.47658029198646545), ('유부', 0.4734435975551605)]

In [586]:
import pandas as pd
import re
from konlpy.tag import Okt

data = recipe_4

# 예외 목록 정의
exceptions = ["된장", "고추장", "참기름", "간장", "모차렐라치즈"]

# 특정 단어 조합 목록 정의
word_combinations = {
    "튀김 가루" : "튀김가루", "북어 포": "북어포", "찹쌀 가루": "찹쌀가루","크리스탈 고운 소금":"소금","닭다리 살":"닭다리살", "파스타 면" : "파스타면", "페이스 트" : "페이스트", "건 표고버섯" : "건표고버섯", "녹말 물" : "녹말물","탕수 소스":"탕수소스","다진 당근":"다진당근","다진 피망":"다진피망","오 겹살":"오겹살","왕만 두":"왕만두","치 커리":"치커리",
    "마늘 솔트":"마늘솔트", "샐러드 드레싱":"샐러드드레싱","레몬 즙" : "레몬즙","통 마늘":"통마늘","다진 대파":"다진대파","다진 마늘":"다진마늘","다진 생강":"다진생강","다진 파":"다진파","용김":"용 김","닭 양념":"닭양념","다진 김치":"다진김치","파 뿌리":"파뿌리","부추 부추 무침":"부추",
    "홍합 살":"홍합살","후추 가루": "후추가루","홀 레인 머스터드":"홀레인머스타드","허니 머스터드":"허니머스타드","다진 양파":"다진양파","체다 치즈":"체다치즈","노란 치즈":"노란치즈","모차렐라 치즈":"모짜렐라치즈","풋 고추":"풋고추","봄 동 잎":"봄동잎","홍차 티백":"홍차티백","군 두":"군만두",
    "청 고추":"청고추","홍 고추":"홍고추","밥 쌀":"밥","모닝 빵":"빵","모짜렐라 치즈":"모짜렐라치즈","커스타드 크림":"커스타드크림","바닐라 오일":"바닐라오일","쌀 가루":"쌀가루","드라이 이스트":"드라이이스트","게 조개":"게조개","계란 노른자":"노른자","카 놀라 유":"카놀라유","꼬막 육수":"꼬막육수",
    "쿠키 반죽":"쿠키반죽","소금 소금":"소금","청 홍고추":"청고추 홍고추","오코노미야키 반죽":"오코노미야키반죽","혼다 시":"혼다시","돈가스 소스":"돈가스소스","만 두피":"만두피","포도 씨유":"포도씨유","제노아 즈":"제노아즈","마늘 대파 소스":"","들깨 가루":"들깨가루","사과 쨈":"사과쩀",
    "꽈리 고추":"꽈리고추","요리 당":"요리당","양념장":"[양념]","양념":"[양념]","재료":"[재료]","월계수 잎":"월계수잎","생강 가루":"생강가루","겨자 가루":"겨자가루","용어 묵":"어묵","캔햄 이나 용햄":"햄","홍시 대 봉시":"홍시 대봉시","매실 엑기스":"매실엑기스","김 가루":"김가루","사골 육수":"사골육수",
    "호박 씨":"호박씨","슈가 파우더":"슈가파우더","단호박 가루":"단호박가루","시나몬 가루":"시나몬가루","반 건조 오징어":"반건조오징어","계란 흰자":"계란흰자","박력":"박력분","박력분분":"박력분","강력":"강력분","베이 킹 파우더":"베이킹파우더","베이 킹 소 다":"베이킹소다","초코 칩":"초코칩","초코 뮈슬리":"초코뮈슬리","두부 면":"두부면",
    "아몬드 크림":"아몬드크림","크림 치즈":"크림치즈","아몬드 가루":"아몬드가루","항정 살이 등심 덧살":"항정살","코코넛 가루":"코코넛가루","플레인 요거트":"플레인요거트","강력분분":"강력분","인 스턴 드":"인스턴트","헤비 위핑크림":"헤비위핑크림","딸기 젤리 [재료]":"[재료]","새 송이버섯":"새송이버섯","국 물":"국물","우동 면":"우동면",
    "마늘 다진것":"다진마늘","밤 페이스트":"밤페이스트","밤 베이킹파우더 계란 우유 밤":"베이킹파우더 계란 우유 밤","건 고추":"건고추","닭 밑":"[닭 밑간]","생강 즙":"생강즙","캬라멜 소스":"카라멜소스","두 툼 하 게":"두툼하게","판 젤라틴":"판젤라틴","생 고등어":"고등어","검은 콩":"검은콩","멸치 육수":"멸치육수",
    "브 리 오슈":"브리오슈","슈거 파우더":"슈가파우더","듬 해물":"모듬해물","양조 간장":"양조간장","실액":"매실액","칵테일 새우":"칵테일새우","육수 새우 머리":"새우머리","피자 피즈":"피자치즈","엔젤 헤어 파스타":"엔젤헤어파스타","시 칠 미":"시칠미","코코아 가루":"코코아가루","바닐라 액":"바닐라액","양파 즙":"양파즙","니 신":"니신","정사 호팬 분량 시트":"",
    "다크 초콜릿":"다크초콜릿","바질 잎":"바질잎","파 마산 치즈":"파마산치즈","올리브유 물 드라이이스트 올리브유":"올리브유","흑 미 가루":"흑미가루","후 랑 크 소세지":"후랑크소세지","진 간장":"진간장","꽃 소금":"꽃소금","딸기 퓨레":"딸기퓨레","미로 와":"미로와","바닐라 엑스 트렉":"바닐라엑스트렉",
    "다시 마물":"다시마물","고추 가루":"고춧가루","튀김 옷":"튀김옷","고운 고춧가루":"고춧가루","다시마 국물":"다시마국물","밥 이랑 밥 뿌려 먹는 가루":"밥에뿌려먹는가루","다시마 육수":"다시마육수","닭 가슴 살캔":"닭가슴살","청 피망":"청피방","홍 피망":"홍피망","완두 콘캔":"완두콩","커스터드 크림 [재료]":"[재료]","샌드 재료":"","닭 안심 살":"닭안심",
    "닭고기 안심 살":"닭고기안심","바베큐 소스":"바베큐소스","오렌지 쥬스":"오렌지주스","식빵 소스":"[식빵 소스]","베이비 채소":"베이비채소","허브 솔트":"허브솔트","호떡 믹스":"호떡믹스","카야 잼":"카야잼","녹차 가루":"녹차가루","딸기 쥬스 가루":"딸기쥬스가루","자숙 문어":"자숙문어","치킨 스톡":"치킨스톡",
    "훈제 닭 가슴 살":"훈제닭가슴살","해바라기 유":"해바라기유","새 조개":"새조개","피 가 얇은 냉동 고기":"","건무 화 과":"무화과","홍 이 장군":"홍이장군","군 고구마":"군고구마","꼬치 소스":"","만두 물만두 고기만 두 물만두 일 때":"만두","스 위트 칠리":"스위트칠리","스프 봉":"","떡국 떡":"떡","묵은 김치":"묵은김치","생 이":"매생이",
    "참치 완 자":"참치완자","적 고구마":"적고구마","국 그릇":"국그릇","따듯 한 물":"따듯한물","다크 쵸콜릿":"다크초콜릿","초코 펜 분홍":"초코펜","부침 가루":"부침가루","늙은 호박":"늙은호박","신 김치":"신김치","국 간장":"국간장","가루 한천":"가루한천","짜장 분말":"짜장분말","반 건조 가자미":"반건조가자미",
    "매실 원 액":"매실원액","두 반장":"두반장","느타리 비섯":"느타리버섯","탕 수 소스":"탕수소스","크 래미":"크래미","카레 가루":"카레가루","왕만두 일반 만두":"만두","김치 고기만 두":"김치만두 고기만두","군 만두":"군만두","민트 잎":"민트잎","파슬리 가루":"파슬리가루","캔햄":"햄","샐러 리":"샐러리",
    "달걀 지단":"달걀지단","다진 돼지고기":"다진돼지고기","다진소고기":"다진소고기","로스 팜 런 천 미트":"","가 쓰 오브 시":"가쓰오부시","백 설탕":"백설탕", "편 마늘":"편마늘","고기만 두":"고기만두","김치 만두":"김치만두","리 챔":"리챔","우리 밀 백 밀가루 중력":"밀가루중력분","후르 츠캔":"후르츠캔","연어 통살캔":"연어캔","노랑 파프리카 파프리카":"노랑파프리카","허니 두 캔더 로프":"허니두캔더로프"}

# 불용어 목록 정의
stopwords = ["컵", "T", "약간", "맘대로", "t", "CC","cc","제일제당","동원","ea","Real","발아현미", "C"," 만들기","동", "s","oz","-","CJ","cm", "L", "등","아빠숟가락","채소", "개", "장", "움큼", "장", "g","먹기", "좋게",  "마리", "쪽", "그외의", "중간짜리", "조금", "S", "or", "담백한","미니","씩","TS",
             "매콤","한","사정", "대로" ,"준비", "하세요","시판","잘","익은","수저","중간크기", "or","이나", "또는", "포기", "중간","큰크기","적당히", "모두가능", "적당", "간","하림","기","데친", "량", "모", "큰", "술", "굵은","토", "핑할", "ml", "김밥", "깍","밑둥", "둑", "썬", "염장", "썬것", "줌", "다듬은",
             "것", "분","스푼","매","중","냉장고","머","든","상관없답니다","향신료","동전굵만큼", "봉지", "kg", "삶은", "양", "ts", "톡톡", "도막","자투리","일반","냉동","백설","다담","캔","그","갓","지은", "외", "의", "야채","용","공기","크게","큰거","떡볶이","통","싱글","팩","샌드위치","작은",
             "조미","걸","로","골","라서","나","조","각","여","불린","토막","한코","찜용","대체","가능","외쌈","알","정도","지을","백세","으","깬것","커스타드크림","국내","산","제빵","그램","인스턴트","조림","좋아하는","종류","줄","오코노미야키반죽","손","줄기","대략","큰것","유기농","잘게","자른",
             "마른","빨강","몸통","만", "사용", "송송", "썬잔","둠","묶음","전장","인","set","G","타르트","지","Ts","각종","당","절임","토핑용","속","에","드실만큼","넣었던","목","안팎","얼린것","고급", "우촌", "생생","숙성","건","이내", "된","ABCT", "남은것","판","종이컵","인분","아무","약","부위",
             "크기","장식","TBSP","꼬집","데코","레이","션","이상","줄줄이","대","사이즈","포","나박","맛","튀김옷","고","밑","껍질","깐","작은것","숭가락","넉넉히","이","찜","tsp","치밥치떡","금기","숟가락","세트","남는","사리","원","클래식","인치", "동전","군","색깔","별로","취향", "껏","저","지방","개정",
             "도","봉","뜯기전","선택","먹고","남은","깉은","생략","mL","많이","삶", "을", "때", "미","샘표","맛있어지는","갈은","고명","갈은","cup","조리", "도구", "나무꼬","기호","봄","숟갈","원칙", "지키는"]

def remove_unwanted_characters(text):
    if text in exceptions:
        return text
    text = re.sub(r'[^\w\s]', '', text)  # 특수 문자 제거
    text = re.sub(r'\d+', '', text)  # 숫자 제거
    text = re.sub(r'[\u2E80-\u2FD5\u3190-\u319f\u3400-\u4DBF\u4E00-\u9FFF\uF900-\uFAFF]', '', text)  # 한자 제거
    return text.strip()

def remove_spaces_for_specific_combinations(text):
    for combo in word_combinations:
        if combo in text:
            text = text.replace(combo, word_combinations[combo])
    return text

def clean_ingredient(ingredient):
    # 예외 목록에 있는 경우, 그대로 반환
    if ingredient in exceptions:
        return ingredient

    ingredient = remove_unwanted_characters(ingredient)
    ingredient = remove_spaces_for_specific_combinations(ingredient)

    # 각 단어별로 불용어 제거
    words = ingredient.split()
    cleaned_words = [word for word in words if word not in stopwords]

    # 정제된 단어들을 다시 합침
    combined_word = ' '.join(cleaned_words)
    if combined_word in exceptions:
        return combined_word

    return combined_word

# 데이터 처리를 수행합니다.
recipe_4['CKG_MTRL_CN'] = recipe_4['CKG_MTRL_CN'].apply(
    lambda x: clean_ingredient(str(x)) if pd.notnull(x) else x
)

# 수정된 코드의 결과를 확인하기 위해 상위 5개 결과를 출력
print(recipe_4['CKG_MTRL_CN'].iloc[23565])
name = recipe_4['CKG_NM'].iloc[23565]
name

[재료] 밥 치킨 양파 계란 [양념] 간장 맛술 설탕

'치킨가라아게동'

In [587]:
similar_words = model.wv.most_similar("참치", topn=10)

# 유사한 단어와 연관된 메뉴명 찾기
for word, similarity in similar_words:
    # 연관된 메뉴명을 찾는 코드를 추가하면 됨
    similar_menus = recipe_4[recipe_4['CKG_MTRL_CN'].str.contains(word, case=False)]
    print(f"Similar Word: {word}, Similarity: {similarity}")
    print("Associated Menus:")
    print(similar_menus[['CKG_NM', 'CKG_MTRL_CN']])
    print("\n")

Similar Word: 캔, Similarity: 0.5942673087120056
Associated Menus:
           CKG_NM                                        CKG_MTRL_CN
1319        후르츠머핀              [재료] 버터 설탕 계란 박력분 베이킹파우더 우유 캔디 드 믹스 필
2019           파이         [재료] 밀가루중력분 레이크 소금 차가운 버터 계란 유정 란 찬물 하드 캔디
5355      닭다리살라자냐  [재료] 닭다리살캔 라자냐 파스타 우유 파슬리가루 피자치즈 [양념] 스파게티 소스 ...
9159        북어포무침                        [재료] 골벵이캔 북어포 소면 초고추장 본문 참조
16949   오미자후르츠팥빙수                      [재료] 오미자 청 물 후르츠캔 빙수 팥 연유 시리얼
17093      복숭아모히또               [재료] 탄산수 민트잎 레몬즙 황도 복숭아 생 블루베리 캔즙 얼음
18568        호박약식  [재료] 찹쌀 백 설탕 소금 물 호두 잣 린밤 캔밤 대추 늙은호박고지 [양념] 단호...
25597      연어야채밥전  [재료] 연어캔 밥 양파 청피방 당근 청양고추 계란 밀가루 빵가루 [양념] 소금 후...
26721    베이컨갈릭콘치즈  [재료] 옥수수 콘캔 양파 노란 파프리카 빨간 파프리카 모짜렐라치즈 기호 베이컨 편...
37885   돌나물골뱅이초무침  [재료] 골뱅이 돌나물 양배추 [양념] 고추장 고춧가루 올리고당 골뱅이 캔속 국물 ...
37941    주꾸미라면파스타  [재료] 주꾸미 라면 봄 적양배추 크림 파스타 소스 병 캔커피 [양념] 버터 다진마...
43007      후루츠사라드                      [재료] 허니두캔더로프 수박 포도 파인애플 체리 딸기
54955     옥수수치즈식빵                         [재료] 식빵 옥수수 캔용 옥수수 체다치즈 설탕
64866      멕시코라이스                         [재료] 멕시코 캔콩 닭 육수 양파 샐러리 버터
72525     호박고지찹쌀떡                   [재료] 찹쌀 볶음 콩가루 호박고지 소금 설탕 캔콩 캔칙빈
88045        호박머핀       [재료] 케익 믹스 호박 퓨레캔 추가 [재료] 바닐라 익스 트랙 트 시나몬 가루
107991      초코크런키                                 [재료] 라면 초코우유 사탕 캔디


Similar Word: 스팸, Similarity: 0.5101264119148254
Associated Menus:
           CKG_NM                                        CKG_MTRL_CN
11         스팸샌드위치      [재료] 스팸 식빵 토마토 상추 치즈 [양념] 홀레인머스타드 허니머스타드 다진양파
14           스팸쌈밥                    [재료] 밥 상추 스팸 밑반찬 [양념] 참기름 맛소금 깨
16        스팸오이식빵롤          [재료] 식빵 스팸 오이 체다치즈 노란치즈 [양념] 머스터드 피클 마요네즈
631      스팸볶음밥그라탕  [재료] 찬밥 스팸 베이컨 청피방 노랑파프리카 애느타리버섯 또띠아 모짜렐라치즈 [양...
685        스팸두부전골  [재료] 스팸 두부 콩나물 애호박 팽이버섯 느타리버섯 홍고추 청고추 대파뿌리 미나리...
...           ...                                                ...
123804     스팸양파볶음                    [재료] 스팸 통마늘 양파 대파 소스 간장 소금 올리고당
123864        달걀쌈  [재료] 달걀 다진양파 다진당근 다진스팸 햄 청양고추 브로콜리 식용유 밥 [양념] ...
123929    계란스팸간장밥                           [재료] 계란 스팸 파 찬밥 간장 참기름 깨
123966    스팸두부짜글이  [재료] 두부 스팸 양파 대파 고추 멸치육수 계란 [양념] 진간장 참치 액 고춧가루...
124339  연어스팸고추장찌개     [재료] 물 감자 호박 양파 스팸 연어 두부 [양념] 고추장 소고기 다시다 마늘 파

[419 rows x 2 columns]


Similar Word: 알래스카, Similarity: 0.5054470896720886
Associated Menus:
Empty DataFrame
Columns: [CKG_NM, CKG_MTRL_CN]
Index: []


Similar Word: 들기름, Similarity: 0.46877360343933105
Associated Menus:
            CKG_NM                                        CKG_MTRL_CN
119          김치볶음밥             [재료] 밥 김치 어묵 계란 파슬리 [양념] 설탕 굴소스 통깨 들기름
158           들깨무국              [재료] 무 다진대파 [양념] 깨 국간장 들기름 다진마늘 볶은 소금
169         시래기들깨탕    [재료] 사골 국물 시래기 대파 [양념] 된장 들기름 다진마늘 들깨가루 소금 후춧가루
354         달래콩나물밥  [재료] 콩나물 달래 당근 [양념] 고춧가루 진간장 다진마늘 깨소금 들기름 참기름 ...
662        감자주먹밥구이  [재료] 밥 감자 김치 [양념] 설탕 들기름 참기름 밥 이랑 밥 뿌려 먹는 가루 기...
...            ...                                                ...
124625  신김치고추장제육볶음  [재료] 돼지고기 삼겹살 신김치 대파 양파 [양념] 고추장 간장 다진마늘 설탕 들기...
124629     양배추어묵잡채  [재료] 양배추 사각 어묵 당근 양파 오이 고추 식용유 [양념] 다진마늘 고운 소금...
124843         상추밥  들깨 소스 들깨가루 마요네즈 레몬즙 설탕 우유 올리고당 간장 검은 깨 맛소금 들기름...
124876   새송이버섯제육볶음  주 [재료] 돼지 목살 새송이버섯 부 [재료] 양파 잔파 [양념] [재료] 고기 재...
124939      쑥갓두부부침  [재료] 두부 쑥갓 들기름 밀가루 계란 [양념] 양조 간장 물 참기름 고춧가루 통깨...

[1587 rows x 2 columns]


Similar Word: 나니, Similarity: 0.4578104019165039
Associated Menus:
         CKG_NM                                        CKG_MTRL_CN
55466  참치맛나니비빔밥  참치 나니 참치 양파 진간장 매실 진액 마늘 깨소금 참치 나니 비빔밥 밥 방 풍 나...


Similar Word: 발아현미, Similarity: 0.44057413935661316
Associated Menus:
Empty DataFrame
Columns: [CKG_NM, CKG_MTRL_CN]
Index: []


Similar Word: 진국, Similarity: 0.43816712498664856
Associated Menus:
          CKG_NM                                        CKG_MTRL_CN
3066        두부찌개        [재료] 두부 대파 [양념] 물 고추장 고춧가루 참치 진국 다진마늘 설탕 소금
3068         토란탕  [재료] 토란 소고기 양지머리 무 짜리 대파 멸치 다시마육수 [양념] 소금 후춧가루...
3232     표고버섯미역국     [재료] 미역 표고버섯 [양념] 다진마늘 참기름 참치 진국 국간장 물 소금 후춧가루
4286    쇠고기배추속대국  [재료] 쇠고기 양지머리 배추속 잎 무 짜리 다시마 짜리 대파 마늘 [양념] 고기 ...
4827     쇠고기콩나물탕  [재료] 콩나물 두부 대파 쇠고기 육수 쇠고기 육수 쇠고기 치마 살 다시마 짜리 통...
4856        쥐포까스  [재료] 쥐포 계란 빵가루 모짜렐라치즈 파슬리가루 식용유 [양념] 스테이크 소스 케...
4971       물미역무침       [재료] 물 미역 오이 [양념] 설탕 식초 고추장 다진마늘 물엿 통깨 참치 진국
5582   백일송이버섯장조림  [재료] 백일 송이 꽈리고추 통마늘 생강 고추 통후추 [양념] 참치 진국 진간장 국...
6421     쭈꾸미샤브샤브  [재료] 쭈꾸미 키조개 새 조개 바지락 해물 칼국수 대파 청경채 버섯 국물 [재료]...
6727    새우오코노미야끼  [재료] 새우 중하 베이컨 양배추 잎 대파 쪽파 반죽 [재료] 부침가루 물 달걀 참...
6728       항정살조림  [재료] 돼지고기 항정 살이 등심 덧살 근 대파 돼지고기 다진마늘 청주 생강즙 이나...
6881       김치감자탕  [재료] 갈비 신김치 감자 깻잎 대파 홍고추 들깨가루 고기 삶는 물 [양념] 물 청...
6882   해물떡볶이치즈구이  [재료] 떡 이나 가래떡 어묵 새우 살 북어 채 양파 팽이버섯 대파 쪽파 물 피자치...
7049        비빔쫄면  [재료] 쫄면 이나 국수 양배추 오이 콩나물 당근 달걀 통깨 참기름 사과 초고추장 ...
7827        무장아찌  [재료] 무 청양고추 무 [재료] 소금 숟갈 설탕 숟갈 간장 물 [재료] 물 간장 ...
8158     닭다리오븐구이  [재료] 닭다리 감자 마늘 오이 및 고추 피클 닭다리 [재료] 허브 맛소금 이나 갈...
8196        가지탕수  [재료] 가지 감자전 숟갈 가지 [재료] 소금 숟갈 후춧가루 소스 [재료] 간장 숟...
15207       김치국수                [재료] 국수 신김치 참기름 김가루 [양념] 참치 진국 깨 소금
55873   황태채고추장무침           [재료] 황태 채 [양념] 매실 청 올리고당 고추장 듬뿍 참치 진국 참깨
63662  김치닭가슴살볶음밥  [재료] 닭가슴살 신김치 데운 밥 분량 다진대파 계란 참치 진국간장 맛술 물엿 참기...
63673   감자참치간장조림  [재료] 감자 다진파 청양고추 참치 양파 표고버섯 당근 [양념] 간장 참치 진국 맛...


Similar Word: 동부, Similarity: 0.4320199489593506
Associated Menus:
          CKG_NM                                        CKG_MTRL_CN
4922      돌나물묵무침  [재료] 돌나물 동부 묵 청포묵 홍고추 청포묵 소금 참기름 [양념] 간장 다진파 고...
6079       청포묵무침                     [재료] 청포묵 동부 묵 김 [양념] 소금 통깨 참기름
6937      동부묵김무침    [재료] 동부 묵 참기름 구이 김 다진대파 실파 [양념] 소금 매매매매매실액 스 통깨
10332  큐브참치동부묵무침      [재료] 큐브 참치 동부 묵 오이 [양념] 진간장 매실 청 다진마늘 참기름 깨소금
98711      동부묵무침                           [재료] 동부 묵 김가루 [양념] 참기름 깨


Similar Word: 뚝심, Similarity: 0.41025206446647644
Associated Menus:
          CKG_NM                                        CKG_MTRL_CN
73187    햄치즈부대라면           [재료] 라면 원칙 지키는 프랑크 원칙 지키는 비엔나 뚝심 대파 치즈 떡
73304   뚝심햄김치볶음밥               [재료] 뚝심 밥 김치 그릇 대파 계란 양파 설탕 참기름 고춧가루
73572     뚝심햄월남쌈                [재료] 뚝심 페이퍼 월남쌈 소스 맞게 파프리카 오이 양파 맛살
78645       햄김치찜                 [재료] 김치 수제 햄 등심 뚝심 대파 팽이버섯 고춧가루 설탕
79112     뚝심마요덮밥               [재료] 계란 따듯 쌀밥 김가루 뚝심 양파 간장 올리고당 마요네즈
84033       햄라자냐  [재료] 주부 단 살코기 햄 뚝심 뿌려 먹는 자연 치즈 스트링치즈 토마토소스 양파 ...
85283      뚝심깻잎전                               [재료] 뚝심 거 깻잎 계란 부침가루
89129     뚝심카레구이                          [재료] 햄 뚝심 계란 파슬리 밀가루 카레가루
89497     봄나물리조또         [재료] 뚝심 햄 치즈 달래 참나물 우유 양파 마늘 후추 소금 올리브오일 밥
91368      두부햄찌개       [재료] 뚝심 햄 두부 멸치 육 수 양파 대파 고춧가루 간장 소금 다진마늘 후추
104988   뚝심고추장찌개  [재료] 뚝심 햇 감자 애호박 두부 표고버섯 대파 다시마 들기름 고춧가루 고추장 설...


Similar Word: 챔, Similarity: 0.40494731068611145
Associated Menus:
              CKG_NM                                        CKG_MTRL_CN
4183          햄또띠아피자  [재료] 또띠아 리챔 혼합 양파 올리브 피자치즈 [양념] 토마토 바질 스파게티 소스...
4252           햄두부찌개  [재료] 리챔 소 두부 양파 애호박 대파 다진 [양념] 멸치육수 고추장 고춧가루 다...
4270         햄치즈퀘사디아                                     [재료] 또띠아 리챔 치즈
4627            햄오믈렛           [재료] 리챔 양파 계란 혼합 당근 피망 옥수수 양파 [양념] 소금 후추
5186         햄토마토파스타    [재료] 스파게티 면 리챔 청피방 홍피망 양파 [양념] 토마토소스 다진마늘 소금 후추
6002            햄말이밥                                       [재료] 리챔 김 찬밥
6610            햄떡볶이  [재료] 리챔 참치 가래떡 당근 새송이버섯 팽이버섯 메추리 [양념] 다시마물 고추장...
6782        햄파프리카월남쌈  [재료] 리챔 당근 파프리카 별 표고 팽이버섯 깻잎 카놀라유 페이퍼 참치 소스 참치...
6873         햄파프리카피자  반죽 [재료] 빵용 밀가루 참치 소금 후추 올리브유 토핑 [재료] 파프리카 노랑 파...
6992          캘리포니아롤  [재료] 밥 오이 맛살 새싹 리챔 날치 김 마요네즈 단촛물 식초 설탕 소금 와사비 ...
7054         햄깻잎달걀말이            [재료] 리챔 깻잎 달걀 식용유 카놀라유 [양념] 연 겨자 매실 청 꿀
7232       파프리카치즈햄말이  [재료] 리챔 오이 양파 작은걸 루 파프리카 별 미나리 체다치즈 식용유 소스 참치 ...
7446    꽈리고추새송이버섯햄볶음           [재료] 리챔 새송이 버섯 꽈리고추 식용유 [양념] 다진마늘 깨소금 후추
7802           햄치즈밥전  [재료] 밥 달걀 치즈 새송이버섯 고추 파프리카 당근 각각 리챔 식용유 [양념] 케...
7855            월남쌈밥  [재료] 페이퍼 오징어 리챔 밥 당근 양파 청고추 홍고추 새송이버섯 [양념] 가스 ...
8074       토마토소시지파스타  [재료] 파스타면 양파 마늘 파프리카 토마토 주스 리챔 [양념] 토마토 케첩 물 고...
8327          닭가슴살만두  만두소 [재료] 닭가슴살 리챔 달걀 양파 마늘 당근 만두피 [재료] 밀가루 물 소금...
8481           햄치즈머핀  [재료] 박력분 파마산치즈 가루 체다치즈 소금 우유 달걀 리챔 식물성 오일 통조림 ...
8783           햄오니기리                         [재료] 흰 쌀밥 리챔 피클 [양념] 참깨 소금
8840            참치볶음  [재료] 델 큐브 참치 리챔 노랑파프리카 청고추 마늘 톨 식용유 [양념] 굴소스 매...
8923           떡볶이꼬치  [재료] 가래떡 리챔 큐브 참치 편마늘 가 쓰 오브 시 육수 견과류 [양념] 고추장...
8996         햄볶음밥그라탕  [재료] 밥 리챔 큐브 참치 브로컬리 당근 파프리카 양파 옥수수 알갱이 체다치즈 피...
9069         소시지야채볶음  [재료] 리챔 비엔나소시지 양파 당근 파프리카 떡 식용유 [양념] 다진마늘 고추장 ...
9120           참치까나페                         [재료] 리챔 큐브 참치 파프리카 아몬드 식용유
9128            섞어찌개  [재료] 리챔 앞다리 살 간거 김치 비엔나 소시지 떡 양파 새송이버섯 부대찌개 콩 ...
9312          감자햄샐러드                   [재료] 리챔 감자 [양념] 마요네즈 통깨 식초 설탕 소금
9352            산적꼬치           [재료] 리챔 맛살 느타리버섯 마늘 쫑 쪽파 계란 포도씨유 [양념] 소금
9435         큐브참치샐러드  [재료] 양상추 리챔 델 큐브 참치 파프리카 밤 브로 커리 거 식용유 [양념] 키위...
9517              밥전             [재료] 밥 리챔 참치 피망 당근 양파 달걀 [양념] 식용유 카놀라유
9671           청경채볶음  [재료] 청경채 새송이버섯 리챔 생강 편 [양념] 굴소스 후추 버섯 물 녹말물 녹말...
10872           비빔당면  [재료] 당면 사각 오뎅 햄 리챔 오이 당근 [양념] 진간장 매실 청 들기름 다진마...
11056           볶음라면          [재료] 라면 리챔 돼지고기 햄 건표고버섯 오징어 간장 소스 간장 물 후추
13905           햄치즈빵  [재료] 강력분 우유 설탕 버터 소금 드라이이스트 [양념] 리챔 체다치즈 허니머스타...
16879           햄감자전                   [재료] 감자 리챔 부침가루 달걀 [양념] 후춧가루 식용유
20659         햄치즈토스트             [재료] 식빵 구워 먹는 치즈 리챔 베이비채소 [양념] 허니 머스타드
25495        하와이언무스비                [재료] 밥 달걀 오이 리챔 김 [양념] 소금 맛술 참기름 통깨
30499         양배추햄덮밥  [재료] 양배추 양파 당근 대파 초록 부분 우유 리챔 청양고추 녹말물 [재료] 녹말...
31362          곤약짜장면         [재료] 양파 당근 양배추 감자 리챔 햄 [양념] 짜장분말 후춧가루 다진마늘
32567         햄오일파스타        [재료] 우유 리챔 스파게티 면 올리브유 통마늘 파슬리가루 [양념] 소금 후추
43326        스팸멸치주먹밥          [재료] 스팸 리챔 브로컬리 당근 피망 김가루 참기름 멸치 볶음 새우 볶음
43869           깻잎햄전                  [재료] 깻잎 햄 리챔 당근 쌀 부침가루 굴소스 물 부침 유
47483           마요덮밥   [재료] 리챔 계란 양파 우유 소금 마요네즈 [양념] 간장 물 맛술 올리고당 식초 후추
52436         복주머니튀김            [재료] 김치 두부 표고버섯 춘권 피 만두피 [양념] 다진대파 챔 기름
82431      스팸고추장감자찌개  [재료] 감자 꽈리고추 리챔 양파 [재료] 포도씨유 간장 참치 액 고추장 다진마늘 ...
85714          햄꼬치튀김           햄 튀김 [재료] 통조림 햄 리챔 곤약 달걀 부침가루 빵가루 식용유 식초
89395         스팸계란밥전                          [재료] 리챔 밥 양파 당근 쪽파 소금 식용유
112117          리챔덮밥       [재료] 양파 대파 리챔 계란 식용유 [양념] 물 고춧가루 간장 올리고당 참기름
113918           밑반찬                    [재료] 리챔 양파 새송이 버섯 계란 [양념] 소금 후추
116514        리챔부대볶음  [재료] 리챔 떡 양파 양배추 대파 참기름 물 식용유 [양념] 고춧가루 고추장 다진...
116578        리챔가지구이                    [재료] 가지 청양고추 홍고추 리챔 계란 튀김가루 식용유
116579        리챔짜장덮밥              [재료] 양파 대파 청양고추 리챔 짜장 가루 식용유 다진마늘 물 밥
118908        리챔감자조림   [재료] 감자 어린이 주먹 리챔 [양념] 진간장 올리고당 설탕 물 건강 유 참기름 통깨
123451       마늘종햄볶음밥  [재료] 마늘 종 리챔 밥 달걀 [양념] 식용유 숟갈 맛소금 후추 굴소스 숟갈 통깨 팍팍

In [588]:
# Set the words for which you want to find similar recipes
words_to_find = ["김치", "두부"]

# Find similar words for each individual word
similar_words = [model.wv.most_similar(word, topn=5) for word in words_to_find]

# Flatten the list of similar words into a set of unique words
unique_words = set(word for sublist in similar_words for word, _ in sublist)

# Create a combined mask for the unique words
combined_mask = recipe_4['CKG_MTRL_CN'].apply(lambda x: all(word in x for word in unique_words))

# Filter the DataFrame based on the combined mask
filtered_recipes = recipe_4[combined_mask]

# Print the sorted recipes
for _, similarity in sorted(similar_words[0], key=lambda x: x[1], reverse=True):
    print(f"\nSimilarity: {similarity}")

    # Print associated menus
    associated_menus = filtered_recipes[filtered_recipes['CKG_MTRL_CN'].str.contains(_, case=False)]

    if not associated_menus.empty:
        print("Associated Menus:")
        print(associated_menus[['CKG_NM', 'CKG_MTRL_CN']])
    else:
        print("No associated menus found.")

Similarity: 0.7069230079650879
No associated menus found.

Similarity: 0.6956360340118408
No associated menus found.

Similarity: 0.6858661770820618
No associated menus found.

Similarity: 0.6279127597808838
No associated menus found.

Similarity: 0.6073418855667114
No associated menus found.

In [589]:
import re

# Function to escape special characters in a string
def escape_special_characters(text):
    special_characters = r"[\^$.|?*+(){}"
    return re.sub(f"[{re.escape(special_characters)}]", r"\\\g<0>", text)

# Example usage:
similar_words = model.wv.most_similar("김치", "간장", topn=5)

# Iterate through similar words and find associated menus
for word, similarity in similar_words:
    # Escape special characters in the word
    escaped_word = escape_special_characters(word)

    # Find associated menus using the escaped word
    similar_menus = recipe_4[recipe_4['CKG_MTRL_CN'].str.contains(escaped_word, case=False)]

    print(f"Similar Word: {word}, Similarity: {similarity}")
    print("Associated Menus:")
    print(similar_menus[['CKG_NM', 'CKG_MTRL_CN']])
    print("\n")

Similar Word: 배추김치, Similarity: 0.42272642254829407
Associated Menus:
               CKG_NM                                        CKG_MTRL_CN
48      소고기크림치즈오븐스파게티      [재료] 배추김치 소고기 체다치즈 스파게티 국수 모짜렐라치즈 [양념] 헤비위핑크림
1077      반건조오징어김치부침개                    [재료] 부침가루 물 배추김치 반건조오징어 어묵 카놀라유
1352           김치만두전골  [재료] 배추김치 돼지고기 만두 파 실파뿌리 팽이버섯 양파 [양념] 다진마늘 간장 ...
2099         참치완자김치찌개  [재료] 배추김치 물 김칫국물 풋고추 대파 식용유 참치완자 참치 두부 양파 밀가루 ...
2320            햄김치찌개   [재료] 배추김치 물 멸치 김칫국물 양파 햄 [양념] 고추장 고춧가루 다진마늘 후춧가루
...               ...                                                ...
121027       열무김치참치볶음  [재료] 열무김치 배추김치 고추 참치 순 살 참치 들기름 다진마늘 매매매매매실액 고...
121040     훈제닭가슴살김치볶음  [재료] 배추김치 훈제닭가슴살 [양념] 진간장 다진마늘 해바라기유 고춧가루 올리고당...
122340        씨앗젓갈주먹밥        [재료] 밥 씨앗 젓갈 김가루 참기름 통깨 설탕 들기름 고춧가루 통깨 배추김치
123310        베이컨김치볶음                 [재료] 배추김치 베이컨 다진파 [양념] 버터 오일 설탕 통깨
124258      새송이버섯김치볶음  주 [재료] 배추김치 혹은 막 김치 국그릇 새송이버섯 [양념] 올리브오일 들깨가루 ...

[171 rows x 2 columns]


Similar Word: 묵은지, Similarity: 0.4046939015388489
Associated Menus:
                 CKG_NM                                        CKG_MTRL_CN
403             묵은지유부초밥              [재료] 초밥 유부 밥 묵은지 파슬리가루 [양념] 기름 설탕 깨소금
463          묵은지삼겹살두루치기  [재료] 삼겹살 묵은김치 양파 묵은지 [양념] 설탕 참 들 기름 삼겹살 [양념] 진...
798             묵은지닭매운탕  [재료] 닭 묵은지 김치 양파 떡 대추 은행 청양고추 참 옻물 김치 국물 [닭 밑간...
1219           묵은지고등어조림  [재료] 고등어 묵은지 무 양파 청양고추 다시마물 [양념] 꽃소금 다진마늘 다진생강...
1576            묵은지삼겹살롤  [재료] 삼겹살 표고버섯 새송이버섯 묵은지 된장 소스 된장 간장 식초 설탕 올리고당...
...                 ...                                                ...
121883  돼지목살묵은지팽이버섯말이구이  [재료] 대패 목살 묵은지 잎 팽이버섯 에서 미나리 있으면 넣으세요 소스 만들기 다...
121923        묵은지김치두루치기  [재료] 돼지고기 목살 미림 후추 묵은지 양파 대파 마늘 다짐 생강 다짐 설탕 고춧...
123468         훈제오리김치찌개                     [재료] 오리 훈제 묵은지 물 마늘 대파 청양 초 홍초
123801        묵은지돼지갈비조림  [재료] la 식 돼지갈비 묵은지 디포 리 육수 양파 대파 식용유 [양념] 다용 무...
124241             묵참말이                  [재료] 묵은지 밥 참치 [양념] 설탕 참기름 통깨 마요네즈

[373 rows x 2 columns]


Similar Word: 익은, Similarity: 0.3820931911468506
Associated Menus:
         CKG_NM                                        CKG_MTRL_CN
16886    김치국수말이  [재료] 소면 배추김치 익은것 냉면 육수 김치 국물 오이 삶은계란 [양념] 참기름 ...
17227      부대볶음  [재료] 후 랑 크 햄 통조림 햄 두부 새송이 어묵 치즈 다진마늘 파뿌리 김치 익은...
21958   두부전김치찌개       [재료] 배추김치 익은거 두 부전 육 전등 명절 음식 재활용 대파 청양고추 마늘
23260    김치유부우동  [재료] 우동면 배추김치 익은것 고춧가루 집 간장 유부 김가루 쪽파 소금 멸치육수 ...
24043     김치참치죽      [재료] 참치 김치 푹 익은것 김치 국물 찬밥 다시마육수 참기름 국간장 맛술 소금
34912    양배추김치전            [재료] 배추김치 익은것 삶은계란 밀가루 중력 밀가루 박력분 식용유 물
39868    쪽갈비김치찜                          [재료] 갈비 김치 팍 익은것 멸치 멸치 가루
52349     목살김치찜  [재료] 돼기 고기 목살 김치 익은것 김치 국물 대파 흰 부분 홍고추 청양고추 다진...
112116  단배추김치볶음                       [재료] 익은단 배추 분량 후추 톡 굴소스 올리고당


Similar Word: 묵은, Similarity: 0.3766360580921173
Associated Menus:
                 CKG_NM                                        CKG_MTRL_CN
403             묵은지유부초밥              [재료] 초밥 유부 밥 묵은지 파슬리가루 [양념] 기름 설탕 깨소금
463          묵은지삼겹살두루치기  [재료] 삼겹살 묵은김치 양파 묵은지 [양념] 설탕 참 들 기름 삼겹살 [양념] 진...
798             묵은지닭매운탕  [재료] 닭 묵은지 김치 양파 떡 대추 은행 청양고추 참 옻물 김치 국물 [닭 밑간...
1219           묵은지고등어조림  [재료] 고등어 묵은지 무 양파 청양고추 다시마물 [양념] 꽃소금 다진마늘 다진생강...
1576            묵은지삼겹살롤  [재료] 삼겹살 표고버섯 새송이버섯 묵은지 된장 소스 된장 간장 식초 설탕 올리고당...
...                 ...                                                ...
121883  돼지목살묵은지팽이버섯말이구이  [재료] 대패 목살 묵은지 잎 팽이버섯 에서 미나리 있으면 넣으세요 소스 만들기 다...
121923        묵은지김치두루치기  [재료] 돼지고기 목살 미림 후추 묵은지 양파 대파 마늘 다짐 생강 다짐 설탕 고춧...
123468         훈제오리김치찌개                     [재료] 오리 훈제 묵은지 물 마늘 대파 청양 초 홍초
123801        묵은지돼지갈비조림  [재료] la 식 돼지갈비 묵은지 디포 리 육수 양파 대파 식용유 [양념] 다용 무...
124241             묵참말이                  [재료] 묵은지 밥 참치 [양념] 설탕 참기름 통깨 마요네즈

[430 rows x 2 columns]


Similar Word: 신, Similarity: 0.3581007719039917
Associated Menus:
            CKG_NM                                        CKG_MTRL_CN
381        김치삼겹살말이             [재료] 삼겹살 깻잎 신김치 [양념] 허브솔트 후춧가루 머스타드 소스
510            돈까스  [재료] 돈까스 등심 신김치 콩나물 홍고추 청고추 통깨 튀김가루 빵가루 계란 [양념...
649        김치감자샐러드  [재료] 신김치 감자 양파 당근 대파 소금물 [재료] 물 소금 마요네즈 소스 마요네...
1320          타코야끼  [재료] 니신 타코야키 분말 찬물 계란 자숙문어 베이컨 실파 양배추 식용유 파래 김...
1365           만두국        [재료] 만두 물 쇠고기 육수 쇠고기 멸치 다 신물 파 달걀 김 [양념] 소금
...            ...                                                ...
122379     삼겹김치말이찜  [재료] 신김치 돼지고기 삼겹살 양파 대파 청양고추 홍고추 김칫국물 물 다시마 멸치...
122649    김치콩나물볶음밥  [재료] 돼지고기 등심 대파 신김치 김치 콩나물 웅큼 고춧가루 밥 설탕 밥 오뎅 우...
124247     신김치들기름찜                 [재료] 신김치 국물 멸치 통깨 [양념] 멸치육수 설탕 들기름
124625  신김치고추장제육볶음  [재료] 돼지고기 삼겹살 신김치 대파 양파 [양념] 고추장 간장 다진마늘 설탕 들기...
124908       김치두부면                     [재료] 두부면 신김치 양파 베이컨 미림 굴소스 참기름

[320 rows x 2 columns]

In [ ]:
similar_words_kimchi_tofu = model.wv.most_similar("고기", "두부", topn=5)

# Get unique words from similar_words
unique_words = set(word for word, _ in similar_words_kimchi_tofu)

# Create a combined mask for the unique words
combined_mask = recipe_4['CKG_MTRL_CN'].apply(lambda x: all(word in x for word in unique_words))

# Filter the DataFrame based on the combined mask
filtered_recipes = recipe_4[combined_mask]

# Print the sorted recipes
for index, (word, similarity) in enumerate(similar_words_kimchi_tofu):
    print(f"\nSimilar Words: {word}, Similarity: {similarity}")

# Print associated menus
if not filtered_recipes.empty:
    print("\nAssociated Menus:")
    print(filtered_recipes[['CKG_NM', 'CKG_MTRL_CN']])
else:
    print("No associated menus found.")

Similar Words: 푸실리/펜네, Similarity: 0.7044182419776917

Similar Words: 3개씩|, Similarity: 0.6925780773162842

Similar Words: 오가닉, Similarity: 0.6908244490623474

Similar Words: [데코], Similarity: 0.687985897064209

Similar Words: [쉘(마카롱, Similarity: 0.6871306896209717
No associated menus found.

In [ ]:
similar_words = model.wv.most_similar("삼겹살", topn=5)

# 유사한 단어와 연관된 메뉴명 찾기
for word, similarity in similar_words:
    # 연관된 메뉴명을 찾는 코드를 추가하면 됨
    similar_menus = recipe_4[recipe_4['CKG_MTRL_CN'].str.contains(word, case=False)]

    # Display only the menu names
    similar_menu_names = similar_menus['CKG_NM'].unique()

    print(f"Similar Word: {word}, Similarity: {similarity}")
    print("Associated Menus:")
    print(similar_menu_names)
    print("\n")

Similar Word: 목살, Similarity: 0.9551011919975281
Associated Menus:
['부추제육볶음' '돼지고기굴소스볶음' '제육볶음' '돼지목살양념구이' '돼지고기두루치기' '떡볶이제육볶음' '돼지고기볶음우동'
 '돼지고추장불고기' '고추장불고기볶음우동' '된장목살구이' '목살스테이크' '폭찹' '돼지목살김치찜' '돼지고기볶음'
 '돼지고기김치두루치기' '비지찌개' '돼지목살된장구이' '대구콩나물찜' '돼지고기맥적' '돼지고기콩비지찌개' '돼지목살두부김치찌개'
 '돼지목살수육' '고추잡채호빵' '달래돼지고기된장구이' '돼지고기카레볶음' '문어동파육' '콩삼불고기' '돼지고기청국장'
 '떡볶이떡사과불고기' '돼지고기생강구이' '돼지갈비구이' '돼지두루치기' '더덕제육볶음' '느타리버섯간장불고기' '목살폭찹'
 '오징어돼지불고기덮밥' '맥적' '깐풍육' '우거지찜' '분짜' '목살폭찹스테이크' '돼지고기두반장볶음' '돼지고기냉채'
 '돼지고기된장구이' '돼지고기된장볶음' '돼지고기고추장감자찌개' '돼지고기오징어볶음' '두릅돼지고기볶음' '간장보쌈'
 '돼지고기마늘구이' '돼지고기목살김치찌개' '삼겹살된장구이' '돼지목살생강조림롤' '봄동돼지고기고추장찌개' '수육' '목살구이'
 '돼지고기감자고추장볶음' '돼지고기야채조림' '돈지루' '맥적구이' '목살찜' '돼지고기제육볶음' '돼지고기맥적구이'
 '부추돼지고기볶음밥' '목살김치찌개' '미나리떡제육볶음' '필라프' '김치돼지고기볶음' '카레목살스테이크' '카레스테이크'
 '목살오븐구이' '목살스테이크샐러드' '목살짜장스테이크' '목살꼬치구이' '돼지고기콩나물찌개' '쌈장주물럭' '돼지고기목살스테이크'
 '오리엔탈비빔쌀국수' '양념갈비' '돼지목살카레' '고기완자전' '목살필라프' '돼지고추장찌개' '끈기덮밥' '고추장목살구이'
 '묵은지돼지김치찜' '된장돼지구이' '돼지고기묵은지쌈' '묵은지목살찜' '돼지목살스테이크' '목살볶음' '소세지김치찌개'
 '돼지목살끈기덮밥' '목살제육볶음' '사과말이튀김' '돼지고기목살불고기' '메로데리야끼구이' '목살스테이크커리'
 '돼지고기숙주볶음밥' '목살고추장찌개' '메로간장조림' '목살양념구이' '중화비빔밥' '목살간장볶음' '목살찹스테이크' '목살카레'
 '고추장돼지고기두루치기' '목살끈기덮밥' '돼지고기목이버섯볶음밥' '오징어제육볶음' '애플포크스테이크' '삼겹살베이글샌드위치'
 '돼지고기배추국' '인삼맥적구이' '대패목살필라프' '목살대파꼬치구이' '목살김치찜' '허니카레라이스' '목살토마토스파게티'
 '돼지고기배추덮밥' '목살덮밥' '대패목살감자채볶음' '돼지목살고추장불고기' '돼지고기알타리김치찜' '콩나물목살찜' '돼지목살구이'
 '목살고추장구이' '오이고추잡채' '목살스테이크양념' '부추깻잎부침개' '대패목살된장찌개' '목살야채꼬치구이' '된장돼지고기구이'
 '등심덮밥' '돼지고기꽈리고추찜' '대패목살고추장비빔밥' '사타이' '대패목살청경채덮밥' '청국장카레' '사과폭찹'
 '돼지목살묵은지찜' '돼지목살고추장구이' '도라지불고기' '보쌈무김치' '연어쿨리비악' '목살케찹볶음' '메로구이간장조림'
 '돈육김치볶음' '양송이목살필라프' '목살돼지갈비' '기름스파게티' '돼지고기숙주부침개' '오징어목살볶음' '토마토돼지고기볶음'
 '카레목살볶음밥' '야끼카레칼국수' '돼지고기목살수육' '돼지고기꽈리고추볶음' '대패목살샌드위치' '양념목살구이'
 '목살스테이크카레' '목살조림' '돼지목살샐러드' '돼지고기목살찹스테이크' '목살당면볶음' '돼지고기김치말이찜'
 '돼지목살김치볶음밥' '돼지목살양배추볶음' '돼지목살폭찹' '두부묵은지지짐' '목살양배추롤' '목살간장불고기' '돼지목살꼬치'
 '수육야채꼬치' '목살차슈덮밥' '파김치돼지고기김치찌개' '김치롤찜' '돼지목살간장불고기' '돼지고기목살김밥' '고기떡볶이'
 '간장목살볶음' '돼지고기목살육전' '돼지목살야채볶음' '목살김치두루치기' '닭목살소금구이' '목살스테이크덮밥'
 '목살스테이크볶음밥' '묵은지김치비지찌개' '수삼수육' '목살김밥' '오징어목살불고기' '파보쌈' '돼지목살야채볶음밥'
 '목살순두부김치찌개' '돼지목살월남쌈' '간장목살구이' '돼지고기양념구이' '돼지고기마늘쫑덮밥' '묵은지돼지목살볶음'
 '목살쌈무말이' '풀드포크' '대파목살양배추볶음' '돼지목살생강구이' '대파목살가지볶음' '목살카레볶음밥' '전주물갈비'
 '김치목살볶음' '목살볶음밥' '목살강정' '건두부목살된장찌개' '목살된장찌개' '돼지목살된장찌개' '그레몰라타돼지목살구이'
 '닭목살구이' '저수분고기채소볶음' '목살된장양념구이' '제육숙주볶음' '매시드포테이토' '돼지고기연근볶음' '대파목살꼬치구이'
 '돼지고기목살덮밥' '레드향소스목살스테이크' '마늘목살볶음' '중국풍돼지볶음조림' '돼지목살떡조림' '대파김치조림'
 '돼지고기목살파채볶음' '대패목살볶음' '돼지목살꿀토스트' '총각무줄기김치찜' '훈제목살김치볶음' '돼지고기젓갈찌개'
 '대패목살덮밥' '냉동목살순두부된장찌개' '바지락짬뽕' '치이바타샌드위치' '돼지목살콩나물불고기' '돼지목살간장구이'
 '목살된장구이' '베이컨달걀밥만두' '스테이크카레' '돼지목살덮밥' '대패목살부추볶음' '꼬치김밥세트' '목살구이카레' '목떡꼬치'
 '통목살수육' '묵은지목살김치찜' '목살간장양념구이' '돼지목살묵은지팽이버섯말이구이' '묵은지김치두루치기' '돼지목살김치말이찜'
 '목살오징어볶음' '새송이버섯제육볶음' '돼지김치전']


Similar Word: 대패삼겹살, Similarity: 0.9523163437843323
Associated Menus:
['삼겹살돌미나리무침' '버섯제육볶음' '철판볶음밥' '묵은지김치찌개' '대패삼겹살' '파채대패삼겹살' '콩나물대패삼겹살찜'
 '제육김밥' '대패삼겹살두루치기' '오돌뼈볶음' '대패삼겹살볶음' '대패삼겹살김치볶음' '대패삼겹살김치찌개' '돼지감자찌개'
 '대패삼겹숙주볶음' '삼겹살오일파스타' '달래삼겹살구이' '부타돈' '대패삼겹살샐러드' '대패삼겹살숙주볶음' '저염쌈장'
 '파채삼겹살' '꼬빔면' '대패삼겹살부추말이' '대패삼겹살튀김' '대패삼겹살덮밥' '대패삼겹살부추양파무침' '대패삼겹살스키야키'
 '고기야채말이' '대패삼겹살불고기' '돼지고기나베' '콩나물대패삼겹살볶음' '대패삼겹살달래무침' '간장콩불' '간장콩나물불고기'
 '대패삼겹살된장찌개' '대패된장찌개' '대패두루치기' '풋마늘삼겹살볶음' '대패삼겹살라볶이' '대패삼겹살두부조림'
 '대패삼겹살비빔밥' '대패삼겹살유부초밥' '대패삼겹살볶음밥' '대패삼겹살팽이버섯말이' '제육쫄볶이' '대패삼겹살샤브샤브'
 '대패삼겹살쪽파말이' '간장대패삼겹살덮밥' '불짬뽕' '삼겹살파채볶음' '생강돼지덮밥' '대패삼겹살간장볶음' '두부삼겹살짜글이'
 '삼겹살불닭말이' '쭈삼볶음' '대패삼겹살숙주찜' '간장대패덮밥' '대패숙주우동볶음' '대패삼겹두루치기' '대패삼겹살삼각김밥'
 '대패삼겹살콩나물불고기' '대패삼겹살매실장아찌무침' '토마토치즈제육덮밥' '삼겹살또띠아피자' '대패삼겹살스팸찌개' '숙주삼겹살'
 '대패삼겹살채소찜' '삼겹살쭈꾸미볶음' '삼겹살단호박조림' '대패삼겹살김치전' '콩불짜글이' '대패삼겹살찜' '양파대패삼겹살볶음'
 '대패삼겹살김치볶음덮밥' '돼지고기삼합' '묵은지돼지고기말이' '대패삼겹살고사리볶음' '푸실리토마토스파게티' '대패삼겹살반미'
 '대패삼겹살가지롤말이' '삼겹살묵은지볶음밥' '마라대패볶음밥' '대패삼겹살콩나물찜' '대패삼겹살청경채볶음' '두릅대패삼겹살말이'
 '대패삼겹살새우말이' '대패삼겹살가지샐러드' '인삼대패팽이버섯말이' '콰트로튀김' '대패삼겹살제육덮밥' '부리또'
 '고추장불고기맥앤치즈' '양파두루치기' '대패짬뽕라면' '양파콩불' '대패삼겹살비지찌개' '배추불고기' '대패삼겹살호박찌개'
 '간장비빔쫄면' '오징어삼겹살쌈밥' '문어삼겹살불고기' '대패삼겹살숙주볶음덮밥' '파불콩' '대패삼겹살파채볶음' '풋고추김밥'
 '풋고추대패삼겹살무침' '풋고추대패삼겹살말이' '풋고추돼지고기냉채' '황제컵밥' '삼겹살매콤소스무침' '냉채대패삼겹'
 '대파삼겹살라면' '비빔면피자' '대패삼겹살김밥' '강된장대패삼겹살덮밥' '대패삼겹살두부찌개' '대패삼겹두부조림'
 '대패삼겹살깻잎튀김' '삼겹살핫도그' '숙주대패삼겹살볶음' '대패삼겹살야채볶음' '대패삼겹살카레오므라이스' '대패삼겹살필라프'
 '대패삼겹살라면' '대패삼겹쭈꾸미볶음' '숙주돼지고기찜' '쟁반짜장면' '대패양덮밥' '대패부추무침' '대패삼겹살파스타'
 '대패삼겹감자짜글이' '꽈리고추대패삼겹살꼬지' '돼지고기채소찜' '대파삼겹살덮밥' '콩나물대패삼겹살' '깍두기김치볶음밥'
 '표고버섯대패덮밥' '대패치즈말이' '팽이버섯대패삼겹살말이' '숙주대패삼겹국밥' '튀김카레' '땅콩대패덮밥' '대삼불초밥'
 '깍두기대패볶음밥' '대패삼겹된장찌개' '양파링삼겹살말이' '두부콩불' '대패삼겹덮밥' '송대삼덮밥' '바짝불고기주먹밥'
 '대패삼겹청경채볶음' '대패삼겹배추볶음' '대패숙주볶음']


Similar Word: 돼지목살, Similarity: 0.9464189410209656
Associated Menus:
['제육볶음' '돼지목살양념구이' '돼지목살김치찜' '돼지목살된장구이' '돼지고기맥적' '고추잡채호빵' '문어동파육' '콩삼불고기'
 '돼지고기목살김치찌개' '봄동돼지고기고추장찌개' '목살김치찌개' '목살꼬치구이' '쌈장주물럭' '돼지목살카레' '고기완자전'
 '돼지목살스테이크' '돼지목살끈기덮밥' '목살제육볶음' '사과말이튀김' '중화비빔밥' '돼지고기배추국' '돼지고기배추덮밥'
 '목살덮밥' '돼지고기알타리김치찜' '콩나물목살찜' '돼지목살구이' '오이고추잡채' '연어쿨리비악' '목살돼지갈비'
 '야끼카레칼국수' '돼지고기목살찹스테이크' '돼지목살김치볶음밥' '돼지목살양배추볶음' '돼지목살간장불고기' '돼지목살야채볶음'
 '목살김밥' '묵은지돼지목살볶음' '풀드포크' '목살카레볶음밥' '김치목살볶음' '목살볶음밥' '건두부목살된장찌개' '목살된장찌개'
 '돼지목살된장찌개' '그레몰라타돼지목살구이' '레드향소스목살스테이크' '돼지목살떡조림' '돼지목살꿀토스트' '돼지목살콩나물불고기'
 '스테이크카레' '새송이버섯제육볶음' '돼지김치전']


Similar Word: 오겹살, Similarity: 0.9381514191627502
Associated Menus:
['베이컨' '된장수육' '쭈꾸미오겹살두루치기' '명이나물마늘보쌈' '오겹살보쌈' '삼합' '갓김치보쌈' '오겹살김치볶음밥'
 '오겹살구이' '오겹살오븐구이' '쑥갓수육' '갑오징어삼겹살볶음' '차슈' '돼지고기묵은지볶음' '오겹살김밥' '오겹살고추장볶음'
 '오겹살고추장찌개' '오겹살수육' '대파수육' '포르케타' '수퍼크리스피삼겹살']


Similar Word: 차돌박이, Similarity: 0.9378501772880554
Associated Menus:
['차돌박이된장찌개' '버섯찌개' '차돌박이고추장찌개' '차돌박이샐러드' '차돌박이샌드위치' '차돌박이구이' '차돌박이비빔국수'
 '차돌박이양념구이' '차돌박이야채샐러드' '차돌박이콩나물겨자무침' '차돌박이베이글샌드위치' '차돌박이묵은지말이구이' '차돌박이'
 '차돌박이된장라면' '차돌박이쌈장' '차돌박이찹쌀구이' '차돌된장찌개' '차돌박이더덕무침' '차돌박이숙주볶음' '차돌박이마늘무침'
 '소고기밀푀유나베' '차돌박이쌀국수' '소고기버섯샤브샤브' '차돌박이파니니' '차돌박이파스타' '차돌박이감자고추장찌개' '춘권'
 '차돌박이콩나물밥' '차돌박이숙주볶음밥' '소고기가지야채말이' '차돌박이덮밥' '차돌박이양파무침' '차돌박이부추무침'
 '차돌박이미나리덮밥' '차돌박이국수' '꽈리고추차돌박이무침' '차돌박이참나물샐러드' '쌈장쌈밥' '차돌박이강된장' '차돌철판볶음밥'
 '차돌박이김치볶음밥' '차돌박이말이' '차돌박이냉채' '차돌박이김밥' '차돌부추비빔국수' '차돌박이볶음된장' '소고기표고버섯덮밥'
 '부추깻잎소고기말이' '차돌박이오므라이스' '차돌박이미역국' '차돌박이감자찌개' '풋마늘차돌박이된장찌개' '차돌박이찜'
 '대파숙주차돌박이말이' '차돌박이스키야키' '차돌말이찜' '차돌박이야채말이찜' '차돌박이가지파스타' '오징어차돌박이불고기'
 '차돌박이공심채볶음' '차돌박이고기국수' '차돌박이부추겉절이' '차돌박이막장찌개' '차돌박이가지볶음' '차돌박이갈릭카레'
 '차돌박이떡볶이' '갈비버섯샤브샤브' '소고기말이찜' '차돌박이김치비빔국수' '차돌박이청국장찌개' '차돌박이볶음밥'
 '차돌박이국물떡볶이' '베이컨볶음말이' '차돌박이로제파스타' '차돌해물된장찌개' '차돌박이짜파게티' '차돌박이두부전골'
 '차돌박이월남쌈' '차돌버섯불고기' '차돌박이부추돌나물무침' '차돌박이부추말이찜' '두릅차돌박이' '두릅차돌박이말이'
 '소고기샐러드쌈' '오징어차돌박이야채볶음' '차돌박이김치볶음' '소고기버섯찜' '차돌삼합' '차돌박이숙주찜' '차돌박이낙지볶음'
 '차돌우거지국' '차돌스팸순두부찌개' '소고기솥밥' '차돌박이크림우동' '차돌박이새우탕면' '차돌박이된장짜글이찌개' '낙차새'
 '차돌박이오징어볶음' '차돌박이부추말이' '차돌박이짬뽕' '차돌박이가지말이' '곰취쌈' '차돌박이야채볶음밥' '차돌박이부추샐러드'
 '차돌박이전골' '차돌박이두부김치' '차돌박이우동볶음' '고기짬뽕' '차돌박이즉석떡볶이' '차돌박이야채말이' '차돌박이청국장'
 '차돌박이부추파전' '차돌박이부추볶음' '양배추롤전' '풋고추차돌박이볶음' '차돌박이잡채' '삼색고추장' '차돌부추리조또'
 '차돌박이얼큰장칼국수' '차돌박이볶음우동' '된장리조또' '달래크림소스파스타' '베트남차돌박이쌀국수' '차돌버섯들깨탕'
 '차돌순두부찌개' '차돌발사믹샐러드김밥' '차돌깍두기볶음밥' '차돌박이김치찌개' '차돌박이냉채유자청' '차돌박이숙주볶음볶음밥'
 '차돌육개장' '차돌박이달래무침' '차돌박이라볶이' '차돌박이알배추찜' '차돌박이냉이된장찌개' '대파차돌박이롤조림'
 '열무참나물비빔국수' '차돌박이두부조림' '냉이차돌박이된장찌개' '차돌박이순두부된장찌개' '쪽파양상추볶음' '차돌박이호박고추장찌개'
 '차돌박이배추전골' '취나물된장비빔국수' '차돌박이볶음짬뽕' '아스파라거스차돌박이말이' '대파차돌박이구이' '마라차돌박이볶음'
 '차돌박이쭈꾸미볶음' '가지차돌잡채덮밥' '가지차돌비빔국수' '차돌박이메밀소바' '차돌박이토마토샐러드' '차돌박이초밥'
 '새우차돌짬뽕' '차돌짬뽕' '차돌박이우동샐러드' '차돌박이비빔면' '송로버섯차돌박이볶음' '차돌김치구이' '차돌박이비빔밥'
 '차돌박이물냉면' '차돌박이된장' '차돌박이쫄면' '차돌박이라면' '고기말이반숙란' '차돌박이부대찌개' '차돌박이된장국'
 '차돌부대찌개' '차돌박이편백찜' '차돌쌀국수' '차돌국물떡볶이' '차돌박이무청시래기밥' '차돌순두부']

In [ ]:
# Take user input for the desired menu
desired_menu = input("Enter the desired menu name: ")

# Find and display the ingredients for the desired menu
desired_menu_data = recipe_4[recipe_4['CKG_NM'].str.contains(desired_menu, case=False)]['CKG_MTRL_CN'].iloc[0]

# Split the data into ingredients and instructions using the pipe character '|'
ingredients, instructions = map(str.strip, desired_menu_data.split('|', 1))

print(f"\nIngredients for {desired_menu}:")
print(ingredients)

print("\nInstructions:")
print(instructions)

Enter the desired menu name: 국물불고기

Ingredients for 국물불고기:
[재료] 국간장 3큰술

Instructions:
간장 3큰술| 청주 3큰술| 참기름 1큰술| 올리고당 1큰술| 매실청 1큰술| 다진마늘 1큰술| 후추 1/2작은술| 소고기 600g| 당면 100g| 다시마 멸치육수 3컵| 버섯 100g| 대파 2대| 숙주 1줌| 소금 약간| 후추 약간

In [ ]:
from konlpy.tag import Okt
from tqdm import tqdm

# Assuming you have already defined 'stopwords'
stopwords = ['|']

# 형태소 분석기 OKT를 사용한 토큰화 작업 (다소 시간 소요)
okt = Okt()

tokenized_data = []
for sentence in tqdm(recipe_4['CKG_MTRL_CN']):
    tokenized_sentence = okt.morphs(sentence, stem=True)  # 토큰화
    stopwords_removed_sentence = [word for word in tokenized_sentence if word not in stopwords]  # 불용어 제거
    tokenized_data.append(stopwords_removed_sentence)

In [ ]:
# Take user input for the desired menu
desired_menu = input("Enter the desired menu name: ")

# Find the index of the desired menu in the original dataset
menu_indices = recipe_4.index[recipe_4['CKG_NM'].str.contains(desired_menu, case=False)].tolist()

if not menu_indices:
    print(f"No menu found with the name '{desired_menu}'.")
else:
    # Use the first index if there are multiple matches (you can adjust this logic as needed)
    menu_index = menu_indices[0]

    # Retrieve the tokenized data for the desired menu
    if 0 <= menu_index < len(tokenized_data):
        desired_menu_tokens = tokenized_data[menu_index]

        # Join the tokens into strings for both ingredients and instructions
        ingredients = ' '.join(desired_menu_tokens)
        instructions = recipe_4['CKG_MTRL_CN'].iloc[menu_index].split('|', 1)[1].strip()

        print(f"\nIngredients for {desired_menu} (after stopword removal):")
        print(ingredients)

        print("\nInstructions:")
        print(instructions)
    else:
        print(f"Invalid menu index: {menu_index}.")

Enter the desired menu name: 국물불고기
Invalid menu index: 78979.

In [ ]:
# Take user input for the desired menu
desired_menu = input("Enter the desired menu name: ")

# Find and display the ingredients for the desired menu
desired_menu_data = recipe_4[recipe_4['CKG_NM'].str.contains(desired_menu, case=False)]['CKG_MTRL_CN'].iloc[0]

# Tokenize the ingredients using Okt
tokenized_ingredients = okt.morphs(desired_menu_data, stem=True)

# Remove stopwords from the tokenized ingredients
filtered_ingredients = ' '.join([word for word in tokenized_ingredients if word not in stopwords])

print(f"\nIngredients for {desired_menu} (after stopword removal):")
print(ingredients)

print("\nInstructions:")
print(instructions)

Enter the desired menu name: 국물불고기

Ingredients for 국물불고기 (after stopword removal):
[재료] 국간장 3큰술

Instructions:
간장 3큰술| 청주 3큰술| 참기름 1큰술| 올리고당 1큰술| 매실청 1큰술| 다진마늘 1큰술| 후추 1/2작은술| 소고기 600g| 당면 100g| 다시마 멸치육수 3컵| 버섯 100g| 대파 2대| 숙주 1줌| 소금 약간| 후추 약간

In [ ]:
# Take user input for the desired menu
desired_menu = input("Enter the desired menu name: ")

# Find and display the ingredients for the desired menu
desired_menu_data = recipe_4[recipe_4['CKG_NM'].str.contains(desired_menu, case=False)][tokenized_data].iloc[0]

# Tokenize the ingredients using Okt
tokenized_ingredients = okt.morphs(desired_menu_data, stem=True)

# Remove stopwords from the tokenized ingredients
filtered_ingredients = ' '.join([word for word in tokenized_ingredients if word not in stopwords])

print(f"\nIngredients for {desired_menu} (after stopword removal):")
print(ingredients)

print("\nInstructions:")
print(instructions)

Enter the desired menu name: 국물불고기

TypeError: ignored

In [ ]:
# Take user input for the desired menu
desired_menu = input("Enter the desired menu name: ")

# Find the index of the desired menu in the original dataset
menu_indices = recipe_4.index[recipe_4['CKG_NM'].str.contains(desired_menu, case=False)].tolist()

if not menu_indices:
    print(f"No menu found with the name '{desired_menu}'.")
else:
    # Use the first index if there are multiple matches (you can adjust this logic as needed)
    menu_index = menu_indices[0]

    # Check if the index is within the range of the tokenized_data list
    if 0 <= menu_index < len(tokenized_data):
        # Retrieve the tokenized data for the desired menu
        desired_menu_tokens = tokenized_data[menu_index]

        # Join the tokens into strings for both ingredients and instructions
        ingredients = ' '.join(desired_menu_tokens)
        instructions = recipe_4['CKG_MTRL_CN'].iloc[menu_index].split('|', 1)[1].strip()

        print(f"\nIngredients for {desired_menu} (after stopword removal):")
        print(ingredients)

        print("\nInstructions:")
        print(instructions)
    else:
        print(f"Invalid menu index: {menu_index}.")

Enter the desired menu name: 국물불고기
Invalid menu index: 78979.